RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(playerData)
    Citizen.Wait(5000)
    print(" ")
    print(" ")
    print("^3Leuk dat je in de console kijkt! Hou jij van dev'n? Solliciteer dan in de support Discord! kronenburgrp.nl/support")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("^3            #                                                                                                           ")
    print("^3           ###               @@   @@@                                                @@                                 ")
    print("^3 %%%#     #####/     ###     @@ @@@                                                  @@                                 ")
    print("^3  %%%%%%.######, ######*     @@@@.     @@@@@@ %@@@@@@   @@@@@@@   @@@@@@@  @@@@@@@,  @@@@@@@@  @@@   @@  @@@@@@ %@@@@@@@")
    print("^3   %%%. #### (#########      @@@@@,    @@.    @@    @@  @@   @@  @@@@@@@@. @@   .@@  @@    @@@ @@@   @@  @@&    @@    @@")
    print("^3    % ##. ############       @@  #@@&  @@.    @@@@@@@#  @@   @@  ,@@# %@@  @@   .@@  @@@@#@@@  #@@@@@@@  @@     @@@@&@@@")
    print("^3      ##############                                                                                             .    @@")
    print("^3                                                                                                                 @@@@@@ ")
    print(" ")
    print(" ")
    print(" ")
end)