--[[ 
	Kronenburg Roleplay
	Copyright © GJSBRT <g@gijs.eu>

	This project is licensed under the terms of the Apache License 2.0 license.
	https://choosealicense.com/licenses/apache-2.0/
]]
 
 
Citizen.CreateThread(function()
    AddTextEntry("rs7r", "Audi RS7 R 2020")
	AddTextEntry("440i", "BMW 440i")
	AddTextEntry("pista", "Ferrari 488 Pista Spyder")
	AddTextEntry("rhapsody", "Renault 5 Turbo")
	AddTextEntry("por718gt4", "Porsche 718 GT4")
	AddTextEntry("720s", "McLaren 720s" )
	AddTextEntry("750li", "BMW 750Li")
	AddTextEntry("seven70", "Ferrari 812 Superfast")
	AddTextEntry("911tbs", "Porsche 911 Turbo")
	AddTextEntry("lwcla45", "Mercedes A45 RocketBunny")
	AddTextEntry("alpinab7", "Aplina B7")
	AddTextEntry("lamboavj", "Lamborghini Aventador SVJ")
	AddTextEntry("bentaygast", "Bently Bentayga")
	AddTextEntry("bmws", "BMW S1000 RR")
	AddTextEntry("brabus500", "Brabus 500")
	AddTextEntry("c8", "Corvette C8")
	AddTextEntry("zl12017", "Chevrolet Camaro ZL1")
	AddTextEntry("pcs18", "Porsche Cayenne S")
	AddTextEntry("rmodlp770", "Lamborghini Centenario")
	AddTextEntry("demon", "Dodge Challenger")
	AddTextEntry("16charger", "Dodge Charger")
	AddTextEntry("chiron5", "Bugatti Chiron")
	AddTextEntry("mesa2", "Renault Clio Sport")
	AddTextEntry("ben17", "Bentley Continental")
	AddTextEntry("rmodbentley1", "Bentley Continental 1ST Edition")
	AddTextEntry("rmodbentleygt", "Bentley Continental GT")
	AddTextEntry("jaguarcx75", "Jaguar CX75")
	AddTextEntry("demonhawkk", "Jeep Demonhawk")
	AddTextEntry("bdivo", "Bugatti Divo")
	AddTextEntry("schafter2", "Mercedes E420")
	AddTextEntry("e63sf", "Mercedes E63S 2020")
	AddTextEntry("mig", "Ferrari Enzo")
	AddTextEntry("kuruma", "Mitsubishi Evo")
	AddTextEntry("jaguarfpace", "Jaguar F-PACE")
	AddTextEntry("f40", "Ferrari F40")
	AddTextEntry("gxg63", "Mercedes G63")
	AddTextEntry("faggio2", "Gilera Runner 180CC")
	AddTextEntry("golfgti7", "Volkswagen Golf 7 GTI")
	AddTextEntry("rmodmk7", "Volkswagen Golf 7 Wide-Body")
	AddTextEntry("gt17", "Ford GT 17")
	AddTextEntry("amgbs", "Mercedes GT R Black Series")
	AddTextEntry("rmodgt63", "Mercedes GT63s")
	AddTextEntry("skyline", "GTR Skyline R34")
	AddTextEntry("gtr", "GTR R35")
	AddTextEntry("HDIron883", "Harley Davidson Iron 883")
	AddTextEntry("flhxs_streetglide_special18", "Harley Davidson Street Glide")
	AddTextEntry("hevo", "Lamborghini Huracan Evo")
	AddTextEntry("18performante", "Lamborghini Huracan Performante")
	AddTextEntry("I8", "i8")
	AddTextEntry("ninjah2", "Kawasaki Ninjah 2")
	AddTextEntry("z1000", "Kawasaki Z1000")
	AddTextEntry("zx10r", "Kawasaki ZX10R")
	AddTextEntry("m3e30", "BMW M3 E30")
	AddTextEntry("m4LB", "BMW M4 Libertywalk")
	AddTextEntry("BMCI", "BMC M5")
	AddTextEntry("16m5", "BMW M5 Touring")
	AddTextEntry("bmwm8", "BMW M8")
	AddTextEntry("bmm", "Bentley Mulsanne Mulliner")
	AddTextEntry("gtmustang", "Ford Mustang GT")
	AddTextEntry("pturismo", "Porsche Panamera Turismo")
	AddTextEntry("phantom8", "Rolls Royce Phantom 8")
	AddTextEntry("polo2018", "Volkswagen Polo")
	AddTextEntry("p7", "Jaguar Project-7")
	AddTextEntry("Q7", "Audi Q7")
	AddTextEntry("r820", "Audi R8 2020")
	AddTextEntry("RS3", "Audi RS3")
	AddTextEntry("AUDIRS6TK", "Audi RS6")
	AddTextEntry("rs6c8", "Audi RS6 Sedan")
	AddTextEntry("audis8om", "Audi S8")
	AddTextEntry("supra2", "Toyota Supra MK.2")
	AddTextEntry("gsxr", "Suzuki GSXR1000")
	AddTextEntry("urus", "Lamborghini Urus")
	AddTextEntry("vantage", "Aston Martin Vantage")
	AddTextEntry("nspeedo", "Vapid Speedo")
	AddTextEntry("18Velar", "Range Rover Velar")
	AddTextEntry("veneno", "Lamborghini Veneno")
	AddTextEntry("x6m", "BMW X6-M")
	AddTextEntry("yz450f", "Yamaha 450F")
	AddTextEntry("r1", "Yamaha R1")
	AddTextEntry("tmax", "Yamaha T-Max 500")
	AddTextEntry("bolide", "Bugatti Bolide")
	AddTextEntry("q820", "Audi Q8 2020")
	AddTextEntry("pmansory", "Porsche Panamera Mansory")
	AddTextEntry("fordDriftFF3", "Ford Mustang FastBack")
	AddTextEntry("monza", "Ferrari Monza SP2")
	AddTextEntry("mcgt20", "2020 McLaren GT")
	AddTextEntry("manscull", "Rolls Royce Mansory Cullinan")
	AddTextEntry("jes", "Jesko 2020")
	AddTextEntry("jesko2020", "Jesko 2020")
	AddTextEntry("JESKO2020X", "Jesko 2020")
	AddTextEntry("HurPerNov", "Lamborghini Huracan Performante Novitech")
	AddTextEntry("huayrar", "Pagani Huayra Roadster")
	AddTextEntry("gemera", "Koenigsegg Gemera")
	AddTextEntry("forgiecat", "Forgiato Hellcat Charger")
	AddTextEntry("trossa", "Ferrari Testarossa")
	AddTextEntry("fm488", "Ferrari 488 Mansory")
	AddTextEntry("dawn", "Rolls Royce Dawn Mansory")
	AddTextEntry("cobra", "Cobra Shelby")
	AddTextEntry("chironss", "Bugatti Chiron SuperSport")
	AddTextEntry("b800f", "Brabus 800 E63")
	AddTextEntry("brabus700", "Brabus 700")
	AddTextEntry("RS62", "Audi RS6 2020")
	AddTextEntry("rs7r", "Audi RS7 2020")
	AddTextEntry("s3sedan", "Audi S3 Sedan")
	AddTextEntry("ar8lb", "Audi R8 LibertyWalk")
	AddTextEntry("develSix", "Devel Sixteen")
	AddTextEntry("toysupmk4", "Toyota Supra MK.4")
	AddTextEntry("bugatticentodieci", "Bugatti Centodieci 2020")
end)