--[[ 
	Kronenburg Roleplay
	Copyright © GJSBRT <g@gijs.eu>

	This project is licensed under the terms of the Apache License 2.0 license.
	https://choosealicense.com/licenses/apache-2.0/
]]
 
 
-- Leaving ban on false is going to log and flag the user, if you want to remove the blacklisted item, you must delete or comment the line

 MyricaBM = {}

 MyricaBM.BlacklistedModels = {
    [GetHashKey("cargoplane")] = {name = "Cargo Plane", ban = true},
    [GetHashKey("dump")] = {name = "Dump", ban = true},
    [GetHashKey("avenger")] = {name = "Avenger", ban = true},
    [GetHashKey("avenger2")] = {name = "Avenger2", ban = true},
    [GetHashKey("luxor")] = {name = "Luxor", ban = true},
    [GetHashKey("khanjali")] = {name = "Khanjali", ban = true},
    [GetHashKey("rhino")] = {name = "Rhino", ban = true},
    [GetHashKey("insurgent")] = {name = "Insurgent", ban = true},
    [GetHashKey("insurgent3")] = {name = "Insurgent3", ban = true},
    [GetHashKey("oppressor")] = {name = "Oprresor", ban = true},
    [GetHashKey("oppressor2")] = {name = "Oprresor2", ban = true},
    [GetHashKey("maverick")] = {name = "Maverick", ban = true},
    [GetHashKey("blimp2")] = {name = "blimp2", ban = true},
    [GetHashKey("blimp")] = {name = "blimp", ban = true},
    [GetHashKey("blimp3")] = {name = "blimp3", ban = true},
    [GetHashKey("freight")] = {name = "Freight", ban = true},
    [GetHashKey("freightcar")] = {name = "FreightCar", ban = true},
    [GetHashKey("limo2")] = {name = "Limo2", ban = true},
    [GetHashKey("freightcont1")] = {name = "FreightCont1", ban = true},
    [GetHashKey("freightcont2")] = {name = "FreightCont2", ban = true},
    [GetHashKey("freightgrain")] = {name = "FreightGrain", ban = true},
    [GetHashKey("cerberus3")] = {name = "Cerberus3", ban = true},
    [GetHashKey("cerberus2")] = {name = "Cerberus2", ban = true},
    [GetHashKey("cerberus")] = {name = "Cerberus", ban = true},
    [GetHashKey("buzzard")] = {name = "Buzzard", ban = true},
    [GetHashKey("phantom2")] = {name = "Phantom2", ban = true},
    [GetHashKey("issi6")] = {name = "Issi6", ban = true},
    [GetHashKey("issi4")] = {name = "Issi4", ban = true},
    [GetHashKey("issi5")] = {name = "Issi5", ban = true},
    [GetHashKey("savage")] = {name = "Savage", ban = true},
    [GetHashKey("hunter")] = {name = "Hunter", ban = true},
    [GetHashKey("akula")] = {name = "Akula", ban = true},
    [GetHashKey("annihilator")] = {name = "Annihilator", ban = true},
    [GetHashKey("cutter")] = {name = "Cutter", ban = true},
    [GetHashKey("bulldozer")] = {name = "Bulldozer", ban = true},
    [GetHashKey("barracks")] = {name = "Barracks", ban = true},
    [GetHashKey("barracks2")] = {name = "Barracks2", ban = true},
    [GetHashKey("barracks3")] = {name = "Barracks3", ban = true},
    [GetHashKey("barrage")] = {name = "Barrage", ban = true},
    [GetHashKey("chernobog")] = {name = "Chernobog", ban = true},
    [GetHashKey("crusader")] = {name = "Crusader", ban = true},
    [GetHashKey("halftrack")] = {name = "HalfTrack", ban = true},
    [GetHashKey("minitank")] = {name = "MiniTank", ban = true},
    [GetHashKey("scarab")] = {name = "Scarab", ban = true},
    [GetHashKey("scarab2")] = {name = "Scarab2", ban = true},
    [GetHashKey("scarab3")] = {name = "Scarab3", ban = true},
    [GetHashKey("thruster")] = {name = "Thruster", ban = true},
    [GetHashKey("trailersmall2")] = {name = "Trailersmall2", ban = true},
    [GetHashKey("brutus3")] = {name = "Brutus3", ban = true},
    [GetHashKey("freecrawler")] = {name = "Freecrawler", ban = true},
    [GetHashKey("monster")] = {name = "Monster", ban = true},
    [GetHashKey("monster3")] = {name = "Monster3", ban = true},
    [GetHashKey("monster4")] = {name = "Monster4", ban = true},
    [GetHashKey("monster5")] = {name = "Monster5", ban = true},
    [GetHashKey("technical")] = {name = "Technical", ban = true},
    [GetHashKey("technical3")] = {name = "Technical3", ban = true},
    [GetHashKey("technical2")] = {name = "Technical2", ban = true},
    [GetHashKey("nightshark")] = {name = "Nightshark", ban = true},
    [GetHashKey("zhaba")] = {name = "Zhaba", ban = true},
    [GetHashKey("formula")] = {name = "Formula", ban = true},
    [GetHashKey("formula2")] = {name = "Formula2", ban = true},
    [GetHashKey("scramjet")] = {name = "Scramjet", ban = true},
    [GetHashKey("zr380")] = {name = "Zr380", ban = true},
    [GetHashKey("zr3802")] = {name = "Zr3802", ban = true},
    [GetHashKey("zr3803")] = {name = "Zr3803", ban = true},
    [GetHashKey("raptor")] = {name = "Raptor", ban = true},
    [GetHashKey("volatol")] = {name = "Volatol", ban = true},
    [GetHashKey("voltic2")] = {name = "Voltic2", ban = true},
    [GetHashKey("tula")] = {name = "Tula", ban = true},
    [GetHashKey("strikeforce")] = {name = "Strikeforce", ban = true},
    [GetHashKey("lazer")] = {name = "Lazer", ban = true},
    [GetHashKey("valkyrie2")] = {name = "Valkyrie2", ban = true},
    [GetHashKey("valkyrie")] = {name = "Valkyrie", ban = true},
    [GetHashKey("jet")] = {name = "Jet", ban = true},
    [GetHashKey("hydra")] = {name = "Hydra", ban = true},
    [GetHashKey("bombushka")] = {name = "Bombushka", ban = true},
    [GetHashKey("bruiser3")] = {name = "Bruiser3", ban = true},
    [GetHashKey("bruiser2")] = {name = "Bruiser2", ban = true},
    [GetHashKey("bruiser")] = {name = "Bruiser", ban = true},
    [GetHashKey("caracara")] = {name = "Caracara", ban = true},
    [GetHashKey("dune5")] = {name = "Dune5", ban = true},
    [GetHashKey("dune4")] = {name = "Dune4", ban = true},
    [GetHashKey("dune3")] = {name = "Dune3", ban = true},
    [GetHashKey("dune2")] = {name = "Dune2", ban = true},
    [GetHashKey("dune")] = {name = "Dune", ban = false},
    [GetHashKey("openwheel1")] = {name = "Openwheel1", ban = true},
    [GetHashKey("paragon2")] = {name = "Paragon2", ban = true},
    [GetHashKey("formula")] = {name = "Formula", ban = true},
    [GetHashKey("formula2")] = {name = "Formula2", ban = true},
    [GetHashKey("blazer5")] = {name = "Blazer5", ban = true},
    [GetHashKey("slamvan4")] = {name = "Slamvan4", ban = true},
    [GetHashKey("slamvan5")] = {name = "Slamvan5", ban = true},
    [GetHashKey("slamvan6")] = {name = "Slamvan6", ban = true},
    [GetHashKey("ruiner2")] = {name = "Ruiner2", ban = true},
    [GetHashKey("dukes2")] = {name = "Dukes2", ban = true},
    [GetHashKey("dominator4")] = {name = "Dominator4", ban = true},
    [GetHashKey("dominator5")] = {name = "Dominator5", ban = true},
    [GetHashKey("dominator6")] = {name = "Dominator6", ban = true},
    [GetHashKey("handler")] = {name = "Handler", ban = true},
    [GetHashKey("vindicator")] = {name = "Vindicator", ban = false},
    [GetHashKey("wastelander")] = {name = "Wastelander", ban = true},
    [GetHashKey("ardent")] = {name = "Ardent", ban = true},
    [GetHashKey("vigilante")] = {name = "Vigilante", ban = true},
 }
 
 MyricaBM.Weapons = {
    [-1357824103] = {name = "weapon_advancedrifle", ban = true}, -- AdvancedRifle
    [-1045183535] = {name = "weapon_revolver", ban = true}, -- Revolver
    [3218215474] = {name = "weapon_snspistol", ban = true}, -- SNSPistol
    [-270015777] = {name = "weapon_assaultsmg", ban = true}, -- AssaultSMG
    [171789620] = {name = "weapon_combatpdw", ban = true}, -- CombatPDW
    [487013001] = {name = "weapon_pumpshotgun", ban = false}, -- PumpShotgun
    [-494615257] = {name = "weapon_assaultshotgun", ban = true}, -- AssaultShotgun
    [-1654528753] = {name = "weapon_bullpupshotgun", ban = true}, -- BullpupShotgun
    [984333226] = {name = "weapon_heavyshotgun", ban = true}, -- HeavyShotgun
    [-1063057011] = {name = "weapon_specialcarbine", ban = true}, -- SpecialCarbine
    [2132975508] = {name = "weapon_bullpuprifle", ban = true}, -- BullpupRifle
    [-1660422300] = {name = "weapon_mg", ban = true}, -- MG
    [2144741730] = {name = "weapon_combatmg", ban = true}, -- CombatMG
    [1627465347] = {name = "weapon_gusenberg", ban = true}, -- Gusenberg
    [205991906] = {name = "weapon_heavysniper", ban = false}, -- HeavySniper
    [-952879014] = {name = "weapon_marksmanrifle", ban = true}, -- MarksmanRifle
    [1119849093] = {name = "weapon_minigun", ban = true}, -- Minigun
    [-1466123874] = {name = "weapon_musket", ban = true}, -- Musket
    [1198879012] = {name = "weapon_flaregun", ban = true}, -- FlareGun
    [-598887786] = {name = "weapon_marksmanpistol", ban = true}, -- MarksmanPistol
    [1834241177] = {name = "weapon_railgun", ban = true}, -- Railgun
    [-275439685] = {name = "weapon_dbshotgun", ban = false}, -- DoubleBarrelShotgun
    [-1746263880] = {name = "weapon_doubleaction", ban = true}, -- Double Action Revolver
    [-2009644972] = {name = "weapon_snspistol_mk2", ban = true}, -- SNS Pistol Mk II
    [-879347409] = {name = "weapon_revolver_mk2", ban = true}, -- Heavy Revolver Mk II
    [-1768145561] = {name = "weapon_specialcarbine_mk2", ban = true}, -- Special Carbine Mk II
    [-2066285827] = {name = "weapon_bullpuprifle_mk2", ban = true}, -- Bullpup Rifle Mk II
    [-608341376] = {name = "weapon_combatmg_mk2", ban = true}, -- Combat MG Mk II
    [177293209] = {name = "weapon_heavysniper_mk2", ban = true}, -- Heavy Sniper Mk II
 }
 
 MyricaBM.BlacklistedObjects = {
    [GetHashKey("prop_fnclink_05crnr1")] = true,
    [GetHashKey("xs_prop_hamburgher_wl")] = true,
    [GetHashKey("xs_prop_plastic_bottle_wl")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("p_spinning_anus_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
    [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
    [GetHashKey("stt_prop_ramp_adj_loop")] = true,
    [GetHashKey("stt_prop_ramp_jump_l")] = true,
    [GetHashKey("stt_prop_ramp_jump_m")] = true,
    [GetHashKey("stt_prop_ramp_jump_s")] = true,
    [GetHashKey("stt_prop_ramp_jump_xl")] = true,
    [GetHashKey("stt_prop_ramp_jump_xs")] = true,
    [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
    [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
    [GetHashKey("stt_prop_ramp_spiral_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_track_start")] = true,
    [GetHashKey("stt_prop_stunt_track_hill2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_gas_pump_1a")] = true,
    [GetHashKey("prop_gas_pump_1b")] = true,
    [GetHashKey("prop_gas_pump_1c")] = true,
    [GetHashKey("prop_gas_pump_1d")] = true,
    [GetHashKey("prop_gas_pump_old2")] = true,
    [GetHashKey("prop_gas_pump_old3")] = true,
    [GetHashKey("prop_vintage_pump")] = true,
    [GetHashKey("apa_mp_h_acc_box_trinket_01")] = true,
    [GetHashKey("prop_roundbailer02")] = true,
    [GetHashKey("prop_roundbailer01")] = true,
    [GetHashKey("prop_roundbailer01")] = true,
    [GetHashKey("-685641702")] = true,
    [GetHashKey("-1230672010")] = true,
    [GetHashKey("-1404869155")] = true,
    [GetHashKey("-759902142")] = true,
    [GetHashKey("prop_fnclink_05crnr1")] = true,
    [GetHashKey("xs_prop_hamburgher_wl")] = true,
    [GetHashKey("xs_prop_plastic_bottle_wl")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("p_spinning_anus_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
    [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
    [GetHashKey("stt_prop_ramp_adj_loop")] = true,
    [GetHashKey("stt_prop_ramp_jump_l")] = true,
    [GetHashKey("stt_prop_ramp_jump_m")] = true,
    [GetHashKey("stt_prop_ramp_jump_s")] = true,
    [GetHashKey("stt_prop_ramp_jump_xl")] = true,
    [GetHashKey("stt_prop_ramp_jump_xs")] = true,
    [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
    [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
    [GetHashKey("stt_prop_ramp_spiral_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_track_start")] = true,
    [GetHashKey("stt_prop_stunt_track_hill2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_gas_pump_1a")] = true,
    [GetHashKey("prop_gas_pump_1b")] = true,
    [GetHashKey("prop_gas_pump_1c")] = true,
    [GetHashKey("prop_gas_pump_1d")] = true,
    [GetHashKey("prop_gas_pump_old2")] = true,
    [GetHashKey("hei_prop_carrier_radar_1_l1")] = true,
    [GetHashKey("v_res_mexball")] = true,
    [GetHashKey("prop_rock_1_a")] = true,
    [GetHashKey("prop_rock_1_b")] = true,
    [GetHashKey("prop_rock_1_c")] = true,
    [GetHashKey("prop_rock_1_d")] = true,
    [GetHashKey("prop_player_gasmask")] = true,
    [GetHashKey("prop_rock_1_e")] = true,
    [GetHashKey("hydra")] = true,
    [GetHashKey("prop_rock_1_f")] = true,
    [GetHashKey("prop_rock_1_g")] = true,
    [GetHashKey("prop_rock_1_h")] = true,
    [GetHashKey("prop_cs_burger_01")] = true,
    [GetHashKey("prop_test_boulder_01")] = true,
    [GetHashKey("prop_test_boulder_02")] = true,
    [GetHashKey("prop_test_boulder_03")] = true,
    [GetHashKey("prop_test_boulder_04")] = true,
    [GetHashKey("apa_mp_apa_crashed_usaf_01a")] = true,
    [GetHashKey("ex_prop_exec_crashdp")] = true,
    [GetHashKey("apa_mp_apa_yacht_o1_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o1_rail_b")] = true,
    [GetHashKey("hei_prop_carrier_radar_1_l1")] = true,
    [GetHashKey("v_res_mexball")] = true,
    [GetHashKey("prop_rock_1_a")] = true,
    [GetHashKey("prop_rock_1_b")] = true,
    [GetHashKey("prop_rock_1_c")] = true,
    [GetHashKey("prop_rock_1_d")] = true,
    [GetHashKey("prop_player_gasmask")] = true,
    [GetHashKey("prop_rock_1_e")] = true,
    [GetHashKey("prop_rock_1_f")] = true,
    [GetHashKey("prop_rock_1_g")] = true,
    [GetHashKey("prop_rock_1_h")] = true,
    [GetHashKey("prop_test_boulder_01")] = true,
    [GetHashKey("prop_test_boulder_02")] = true,
    [GetHashKey("prop_test_boulder_03")] = true,
    [GetHashKey("prop_test_boulder_04")] = true,
    [GetHashKey("apa_mp_apa_crashed_usaf_01a")] = true,
    [GetHashKey("ex_prop_exec_crashdp")] = true,
    [GetHashKey("apa_mp_apa_yacht_o1_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o1_rail_b")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_01")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_03")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_04")] = true,
    [GetHashKey("apa_mp_h_yacht_barstool_01")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_01")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_02")] = true,
    [GetHashKey("apa_mp_h_yacht_coffee_table_01")] = true,
    [GetHashKey("apa_mp_h_yacht_coffee_table_02")] = true,
    [GetHashKey("apa_mp_h_yacht_floor_lamp_01")] = true,
    [GetHashKey("apa_mp_h_yacht_side_table_01")] = true,
    [GetHashKey("apa_mp_h_yacht_side_table_02")] = true,
    [GetHashKey("apa_mp_h_yacht_sofa_01")] = true,
    [GetHashKey("apa_mp_h_yacht_sofa_02")] = true,
    [GetHashKey("apa_mp_h_yacht_stool_01")] = true,
    [GetHashKey("apa_mp_h_yacht_strip_chair_01")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_01")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_02")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_03")] = true,
    [GetHashKey("prop_flag_columbia")] = true,
    [GetHashKey("apa_mp_apa_yacht_o2_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o2_rail_b")] = true,
    [GetHashKey("apa_mp_apa_yacht_o3_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o3_rail_b")] = true,
    [GetHashKey("apa_mp_apa_yacht_option1")] = true,
    [GetHashKey("proc_searock_01")] = true,
    [GetHashKey("apa_mp_h_yacht_")] = true,
    [GetHashKey("apa_mp_apa_yacht_option1_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2_colb")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_colb")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_colc")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cold")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cole")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_cam")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple003")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple1")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple2")] = true,
    [GetHashKey("apa_mp_apa_yacht_radar_01a")] = true,
    [GetHashKey("apa_mp_apa_yacht_win")] = true,
    [GetHashKey("prop_crashed_heli")] = true,
    [GetHashKey("apa_mp_apa_yacht_door")] = true,
    [GetHashKey("prop_shamal_crash")] = true,
    [GetHashKey("xm_prop_x17_shamal_crash")] = true,
    [GetHashKey("apa_mp_apa_yacht_door2")] = true,
    [GetHashKey("apa_mp_apa_yacht")] = true,
    [GetHashKey("prop_flagpole_2b")] = true,
    [GetHashKey("prop_flagpole_2c")] = true,
    [GetHashKey("prop_flag_canada")] = true,
    [GetHashKey("apa_prop_yacht_float_1a")] = true,
    [GetHashKey("apa_prop_yacht_float_1b")] = true,
    [GetHashKey("apa_prop_yacht_glass_01")] = true,
    [GetHashKey("apa_prop_yacht_glass_02")] = true,
    [GetHashKey("apa_prop_yacht_glass_03")] = true,
    [GetHashKey("apa_prop_yacht_glass_04")] = true,
    [GetHashKey("apa_prop_yacht_glass_05")] = true,
    [GetHashKey("apa_prop_yacht_glass_06")] = true,
    [GetHashKey("apa_prop_yacht_glass_07")] = true,
    [GetHashKey("apa_prop_yacht_glass_08")] = true,
    [GetHashKey("apa_prop_yacht_glass_09")] = true,
    [GetHashKey("apa_prop_yacht_glass_10")] = true,
    [GetHashKey("prop_flag_canada_s")] = true,
    [GetHashKey("prop_flag_eu")] = true,
    [GetHashKey("prop_flag_eu_s")] = true,
    [GetHashKey("prop_target_blue_arrow")] = true,
    [GetHashKey("prop_target_orange_arrow")] = true,
    [GetHashKey("prop_target_purp_arrow")] = true,
    [GetHashKey("prop_target_red_arrow")] = true,
    [GetHashKey("apa_prop_flag_argentina")] = true,
    [GetHashKey("apa_prop_flag_australia")] = true,
    [GetHashKey("apa_prop_flag_austria")] = true,
    [GetHashKey("apa_prop_flag_belgium")] = true,
    [GetHashKey("apa_prop_flag_brazil")] = true,
    [GetHashKey("apa_prop_flag_canadat_yt")] = true,
    [GetHashKey("apa_prop_flag_china")] = true,
    [GetHashKey("apa_prop_flag_columbia")] = true,
    [GetHashKey("apa_prop_flag_croatia")] = true,
    [GetHashKey("apa_prop_flag_czechrep")] = true,
    [GetHashKey("apa_prop_flag_denmark")] = true,
    [GetHashKey("apa_prop_flag_england")] = true,
    [GetHashKey("apa_prop_flag_eu_yt")] = true,
    [GetHashKey("apa_prop_flag_finland")] = true,
    [GetHashKey("apa_prop_flag_france")] = true,
    [GetHashKey("apa_prop_flag_german_yt")] = true,
    [GetHashKey("apa_prop_flag_hungary")] = true,
    [GetHashKey("apa_prop_flag_ireland")] = true,
    [GetHashKey("apa_prop_flag_israel")] = true,
    [GetHashKey("apa_prop_flag_italy")] = true,
    [GetHashKey("apa_prop_flag_jamaica")] = true,
    [GetHashKey("apa_prop_flag_japan_yt")] = true,
    [GetHashKey("apa_prop_flag_canada_yt")] = true,
    [GetHashKey("apa_prop_flag_lstein")] = true,
    [GetHashKey("apa_prop_flag_malta")] = true,
    [GetHashKey("apa_prop_flag_mexico_yt")] = true,
    [GetHashKey("apa_prop_flag_netherlands")] = true,
    [GetHashKey("apa_prop_flag_newzealand")] = true,
    [GetHashKey("apa_prop_flag_nigeria")] = true,
    [GetHashKey("apa_prop_flag_norway")] = true,
    [GetHashKey("apa_prop_flag_palestine")] = true,
    [GetHashKey("apa_prop_flag_poland")] = true,
    [GetHashKey("apa_prop_flag_portugal")] = true,
    [GetHashKey("apa_prop_flag_puertorico")] = true,
    [GetHashKey("apa_prop_flag_russia_yt")] = true,
    [GetHashKey("apa_prop_flag_scotland_yt")] = true,
    [GetHashKey("apa_prop_flag_script")] = true,
    [GetHashKey("apa_prop_flag_slovakia")] = true,
    [GetHashKey("apa_prop_flag_slovenia")] = true,
    [GetHashKey("apa_prop_flag_southafrica")] = true,
    [GetHashKey("apa_prop_flag_southkorea")] = true,
    [GetHashKey("apa_prop_flag_spain")] = true,
    [GetHashKey("apa_prop_flag_sweden")] = true,
    [GetHashKey("apa_prop_flag_switzerland")] = true,
    [GetHashKey("apa_prop_flag_turkey")] = true,
    [GetHashKey("apa_prop_flag_uk_yt")] = true,
    [GetHashKey("apa_prop_flag_us_yt")] = true,
    [GetHashKey("apa_prop_flag_wales")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("prop_flag_france")] = true,
    [GetHashKey("prop_flag_france_s")] = true,
    [GetHashKey("prop_flag_german")] = true,
    [GetHashKey("prop_flag_german_s")] = true,
    [GetHashKey("prop_flag_ireland")] = true,
    [GetHashKey("prop_flag_ireland_s")] = true,
    [GetHashKey("prop_flag_japan")] = true,
    [GetHashKey("prop_flag_japan_s")] = true,
    [GetHashKey("prop_flag_ls")] = true,
    [GetHashKey("prop_flag_lsfd")] = true,
    [GetHashKey("prop_flag_lsfd_s")] = true,
    [GetHashKey("prop_flag_lsservices")] = true,
    [GetHashKey("prop_flag_lsservices_s")] = true,
    [GetHashKey("prop_flag_ls_s")] = true,
    [GetHashKey("prop_flag_mexico")] = true,
    [GetHashKey("prop_flag_mexico_s")] = true,
    [GetHashKey("prop_flag_russia")] = true,
    [GetHashKey("prop_flag_russia_s")] = true,
    [GetHashKey("prop_flag_s")] = true,
    [GetHashKey("prop_flag_sa")] = true,
    [GetHashKey("prop_flag_sapd")] = true,
    [GetHashKey("prop_flag_sapd_s")] = true,
    [GetHashKey("prop_flag_sa_s")] = true,
    [GetHashKey("prop_flag_scotland")] = true,
    [GetHashKey("prop_flag_scotland_s")] = true,
    [GetHashKey("prop_flag_sheriff")] = true,
    [GetHashKey("prop_flag_sheriff_s")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("prop_flamingo")] = true,
    [GetHashKey("prop_swiss_ball_01")] = true,
    [GetHashKey("prop_air_bigradar_l1")] = true,
    [GetHashKey("prop_air_bigradar_l2")] = true,
    [GetHashKey("prop_air_bigradar_slod")] = true,
    [GetHashKey("p_fib_rubble_s")] = true,
    [GetHashKey("prop_money_bag_01")] = true,
    [GetHashKey("p_cs_mp_jet_01_s")] = true,
    [GetHashKey("prop_poly_bag_money")] = true,
    [GetHashKey("prop_air_radar_01")] = true,
    [GetHashKey("hei_prop_carrier_radar_1")] = true,
    [GetHashKey("prop_air_bigradar")] = true,
    [GetHashKey("prop_carrier_radar_1_l1")] = true,
    [GetHashKey("prop_asteroid_01")] = true,
    [GetHashKey("prop_xmas_ext")] = true,
    [GetHashKey("p_oil_pjack_01_amo")] = true,
    [GetHashKey("p_oil_pjack_01_s")] = true,
    [GetHashKey("p_oil_pjack_02_amo")] = true,
    [GetHashKey("p_oil_pjack_03_amo")] = true,
    [GetHashKey("p_oil_pjack_02_s")] = true,
    [GetHashKey("p_oil_pjack_03_s")] = true,
    [GetHashKey("prop_aircon_l_03")] = true,
    [GetHashKey("prop_med_jet_01")] = true,
    [GetHashKey("p_med_jet_01_s")] = true,
    [GetHashKey("hei_prop_carrier_jet")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_01")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_02")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_04")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_05")] = true,
    [GetHashKey("hei_prop_heist_emp")] = true,
    [GetHashKey("prop_weed_01")] = true,
    [GetHashKey("prop_air_bigradar")] = true,
    [GetHashKey("prop_juicestand")] = true,
    [GetHashKey("prop_lev_des_barge_02")] = true,
    [GetHashKey("hei_prop_carrier_defense_01")] = true,
    [GetHashKey("prop_aircon_m_04")] = true,
    [GetHashKey("prop_mp_ramp_03")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("ch3_12_animplane1_lod")] = true,
    [GetHashKey("ch3_12_animplane2_lod")] = true,
    [GetHashKey("hei_prop_hei_pic_pb_plane")] = true,
    [GetHashKey("light_plane_rig")] = true,
    [GetHashKey("prop_cs_plane_int_01")] = true,
    [GetHashKey("prop_dummy_plane")] = true,
    [GetHashKey("prop_mk_plane")] = true,
    [GetHashKey("v_44_planeticket")] = true,
    [GetHashKey("prop_planer_01")] = true,
    [GetHashKey("ch3_03_cliffrocks03b_lod")] = true,
    [GetHashKey("ch3_04_rock_lod_02")] = true,
    [GetHashKey("csx_coastsmalrock_01_")] = true,
    [GetHashKey("csx_coastsmalrock_02_")] = true,
    [GetHashKey("csx_coastsmalrock_03_")] = true,
    [GetHashKey("csx_coastsmalrock_04_")] = true,
    [GetHashKey("mp_player_introck")] = true,
    [GetHashKey("Heist_Yacht")] = true,
    [GetHashKey("csx_coastsmalrock_05_")] = true,
    [GetHashKey("mp_player_int_rock")] = true,
    [GetHashKey("mp_player_introck")] = true,
    [GetHashKey("prop_flagpole_1a")] = true,
    [GetHashKey("prop_flagpole_2a")] = true,
    [GetHashKey("prop_flagpole_3a")] = true,
    [GetHashKey("prop_a4_pile_01")] = true,
    [GetHashKey("cs2_10_sea_rocks_lod")] = true,
    [GetHashKey("cs2_11_sea_marina_xr_rocks_03_lod")] = true,
    [GetHashKey("prop_gold_cont_01")] = true,
    [GetHashKey("prop_hydro_platform")] = true,
    [GetHashKey("ch3_04_viewplatform_slod")] = true,
    [GetHashKey("ch2_03c_rnchstones_lod")] = true,
    [GetHashKey("proc_mntn_stone01")] = true,
    [GetHashKey("dt1_05_build1_damage")] = true,
    [GetHashKey("prop_beachflag_le")] = true,
    [GetHashKey("proc_mntn_stone02")] = true,
    [GetHashKey("cs2_10_sea_shipwreck_lod")] = true,
    [GetHashKey("des_shipsink_02")] = true,
    [GetHashKey("prop_dock_shippad")] = true,
    [GetHashKey("des_shipsink_03")] = true,
    [GetHashKey("des_shipsink_04")] = true,
    [GetHashKey("prop_mk_flag")] = true,
    [GetHashKey("prop_mk_flag_2")] = true,
    [GetHashKey("proc_mntn_stone03")] = true,
    [GetHashKey("FreeModeMale01")] = true,
    [GetHashKey("rsn_os_specialfloatymetal_n")] = true,
    [GetHashKey("rsn_os_specialfloatymetal")] = true,
    [GetHashKey("cs1_09_sea_ufo")] = true,
    [GetHashKey("rsn_os_specialfloaty2_light2")] = true,
    [GetHashKey("rsn_os_specialfloaty2_light")] = true,
    [GetHashKey("rsn_os_specialfloaty2")] = true,
    [GetHashKey("rsn_os_specialfloatymetal_n")] = true,
    [GetHashKey("rsn_os_specialfloatymetal")] = true,
    [GetHashKey("P_Spinning_Anus_S_Main")] = true,
    [GetHashKey("P_Spinning_Anus_S_Root")] = true,
    [GetHashKey("cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a")] = true,
    [GetHashKey("sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a")] = true,
    [GetHashKey("rnbj_wallsigns_0001")] = true,
    [GetHashKey("proc_sml_stones01")] = true,
    [GetHashKey("proc_sml_stones02")] = true,
    [GetHashKey("maverick")] = true,
    [GetHashKey("Miljet")] = true,
    [GetHashKey("proc_sml_stones03")] = true,
    [GetHashKey("proc_stones_01")] = true,
    [GetHashKey("proc_stones_02")] = true,
    [GetHashKey("proc_stones_03")] = true,
    [GetHashKey("proc_stones_04")] = true,
    [GetHashKey("proc_stones_05")] = true,
    [GetHashKey("proc_stones_06")] = true,
    [GetHashKey("prop_coral_stone_03")] = true,
    [GetHashKey("prop_coral_stone_04")] = true,
    [GetHashKey("prop_gravestones_01a")] = true,
    [GetHashKey("prop_gravestones_02a")] = true,
    [GetHashKey("prop_gravestones_03a")] = true,
    [GetHashKey("prop_gravestones_04a")] = true,
    [GetHashKey("prop_gravestones_05a")] = true,
    [GetHashKey("prop_gravestones_06a")] = true,
    [GetHashKey("prop_gravestones_07a")] = true,
    [GetHashKey("prop_gravestones_08a")] = true,
    [GetHashKey("prop_gravestones_09a")] = true,
    [GetHashKey("prop_gravestones_10a")] = true,
    [GetHashKey("prop_prlg_gravestone_05a_l1")] = true,
    [GetHashKey("prop_prlg_gravestone_06a")] = true,
    [GetHashKey("test_prop_gravestones_04a")] = true,
    [GetHashKey("test_prop_gravestones_05a")] = true,
    [GetHashKey("test_prop_gravestones_07a")] = true,
    [GetHashKey("test_prop_gravestones_08a")] = true,
    [GetHashKey("test_prop_gravestones_09a")] = true,
    [GetHashKey("prop_prlg_gravestone_01a")] = true,
    [GetHashKey("prop_prlg_gravestone_02a")] = true,
    [GetHashKey("prop_prlg_gravestone_03a")] = true,
    [GetHashKey("prop_prlg_gravestone_04a")] = true,
    [GetHashKey("prop_stoneshroom1")] = true,
    [GetHashKey("prop_stoneshroom2")] = true,
    [GetHashKey("v_res_fa_stones01")] = true,
    [GetHashKey("test_prop_gravestones_01a")] = true,
    [GetHashKey("test_prop_gravestones_02a")] = true,
    [GetHashKey("prop_prlg_gravestone_05a")] = true,
    [GetHashKey("FreemodeFemale01")] = true,
    [GetHashKey("p_cablecar_s")] = true,
    [GetHashKey("stt_prop_stunt_tube_l")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("p_spinning_anus_s")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("hei_prop_heist_tug")] = true,
    [GetHashKey("prop_air_bigradar")] = true,
    [GetHashKey("p_oil_slick_01")] = true,
    [GetHashKey("prop_dummy_01")] = true,
    [GetHashKey("hei_prop_heist_emp")] = true,
    [GetHashKey("p_tram_cash_s")] = true,
    [GetHashKey("hw1_blimp_ce2")] = true,
    [GetHashKey("prop_fire_exting_1a")] = true,
    [GetHashKey("prop_fire_exting_1b")] = true,
    [GetHashKey("prop_fire_exting_2a")] = true,
    [GetHashKey("prop_fire_exting_3a")] = true,
    [GetHashKey("hw1_blimp_ce2_lod")] = true,
    [GetHashKey("hw1_blimp_ce_lod")] = true,
    [GetHashKey("hw1_blimp_cpr003")] = true,
    [GetHashKey("hw1_blimp_cpr_null")] = true,
    [GetHashKey("hw1_blimp_cpr_null2")] = true,
    [GetHashKey("prop_lev_des_barage_02")] = true,
    [GetHashKey("hei_prop_carrier_defense_01")] = true,
    [GetHashKey("prop_juicestand")] = true,
    [GetHashKey("S_M_M_MovAlien_01")] = true,
    [GetHashKey("s_m_m_movalien_01")] = true,
    [GetHashKey("s_m_m_movallien_01")] = true,
    [GetHashKey("u_m_y_babyd")] = true,
    [GetHashKey("CS_Orleans")] = true,
    [GetHashKey("A_M_Y_ACult_01")] = true,
    [GetHashKey("S_M_M_MovSpace_01")] = true,
    [GetHashKey("U_M_Y_Zombie_01")] = true,
    [GetHashKey("s_m_y_blackops_01")] = true,
    [GetHashKey("a_f_y_topless_01")] = true,
    [GetHashKey("a_c_boar")] = true,
    [GetHashKey("a_c_chickenhawk")] = true,
    [GetHashKey("a_c_chimp")] = true,
    [GetHashKey("s_f_y_hooker_03")] = true,
    [GetHashKey("a_c_chop")] = true,
    [GetHashKey("a_c_cormorant")] = true,
    [GetHashKey("a_c_cow")] = true,
    [GetHashKey("a_c_coyote")] = true,
    [GetHashKey("v_ilev_found_cranebucket")] = true,
    [GetHashKey("p_cs_sub_hook_01_s")] = true,
    [GetHashKey("a_c_crow")] = true,
    [GetHashKey("a_c_dolphin")] = true,
    [GetHashKey("a_c_fish")] = true,
    [GetHashKey("hei_prop_heist_hook_01")] = true,
    [GetHashKey("prop_rope_hook_01")] = true,
    [GetHashKey("prop_sub_crane_hook")] = true,
    [GetHashKey("s_f_y_hooker_01")] = true,
    [GetHashKey("prop_vehicle_hook")] = true,
    [GetHashKey("prop_v_hook_s")] = true,
    [GetHashKey("prop_dock_crane_02_hook")] = true,
    [GetHashKey("prop_winch_hook_long")] = true,
    [GetHashKey("a_c_hen")] = true,
    [GetHashKey("a_c_humpback")] = true,
    [GetHashKey("a_c_killerwhale")] = true,
    [GetHashKey("a_c_mtlion")] = true,
    [GetHashKey("prop_coathook_01")] = true,
    [GetHashKey("prop_cs_sub_hook_01")] = true,
    [GetHashKey("a_c_rabbit_01")] = true,
    [GetHashKey("a_c_rhesus")] = true,
    [GetHashKey("a_c_sharkhammer")] = true,
    [GetHashKey("a_c_sharktiger")] = true,
    [GetHashKey("a_c_stingray")] = true,
    [GetHashKey("CS_Orleans")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("prop_Ld_ferris_wheel")] = true,
    [GetHashKey("p_tram_crash_s")] = true,
    [GetHashKey("p_oil_slick_01")] = true,
    [GetHashKey("p_ld_stinger_s")] = true,
    [GetHashKey("p_parachute1_s")] = true,
    [GetHashKey("p_cablecar_s")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_lev_des_barge_02")] = true,
    [GetHashKey("prop_lev_des_barge_01")] = true,
    [GetHashKey("prop_sculpt_fix")] = true,
    [GetHashKey("prop_flagpole_2b")] = true,
    [GetHashKey("prop_flagpole_2c")] = true,
    [GetHashKey("prop_winch_hook_short")] = true,
    [GetHashKey("prop_flag_canada")] = true,
    [GetHashKey("prop_flag_canada_s")] = true,
    [GetHashKey("prop_flag_eu")] = true,
    [GetHashKey("prop_flag_eu_s")] = true,
    [GetHashKey("prop_flag_france")] = true,
    [GetHashKey("prop_flag_france_s")] = true,
    [GetHashKey("prop_flag_german")] = true,
    [GetHashKey("prop_ld_hook")] = true,
    [GetHashKey("prop_flag_german_s")] = true,
    [GetHashKey("prop_flag_ireland")] = true,
    [GetHashKey("prop_flag_ireland_s")] = true,
    [GetHashKey("prop_flag_japan")] = true,
    [GetHashKey("prop_flag_japan_s")] = true,
    [GetHashKey("prop_flag_ls")] = true,
    [GetHashKey("prop_flag_lsfd")] = true,
    [GetHashKey("prop_flag_lsfd_s")] = true,
    [GetHashKey("prop_cable_hook_01")] = true,
    [GetHashKey("prop_flag_lsservices")] = true,
    [GetHashKey("prop_flag_lsservices_s")] = true,
    [GetHashKey("prop_flag_ls_s")] = true,
    [GetHashKey("prop_flag_mexico")] = true,
    [GetHashKey("prop_flag_mexico_s")] = true,
    [GetHashKey("csx_coastboulder_00")] = true,
    [GetHashKey("des_tankercrash_01")] = true,
    [GetHashKey("des_tankerexplosion_01")] = true,
    [GetHashKey("des_tankerexplosion_02")] = true,
    [GetHashKey("des_trailerparka_02")] = true,
    [GetHashKey("des_trailerparkb_02")] = true,
    [GetHashKey("des_trailerparkc_02")] = true,
    [GetHashKey("des_trailerparkd_02")] = true,
    [GetHashKey("des_traincrash_root2")] = true,
    [GetHashKey("des_traincrash_root3")] = true,
    [GetHashKey("des_traincrash_root4")] = true,
    [GetHashKey("des_traincrash_root5")] = true,
    [GetHashKey("des_finale_vault_end")] = true,
    [GetHashKey("des_finale_vault_root001")] = true,
    [GetHashKey("des_finale_vault_root002")] = true,
    [GetHashKey("des_finale_vault_root003")] = true,
    [GetHashKey("des_finale_vault_root004")] = true,
    [GetHashKey("des_finale_vault_start")] = true,
    [GetHashKey("des_vaultdoor001_root001")] = true,
    [GetHashKey("des_vaultdoor001_root002")] = true,
    [GetHashKey("des_vaultdoor001_root003")] = true,
    [GetHashKey("des_vaultdoor001_root004")] = true,
    [GetHashKey("des_vaultdoor001_root005")] = true,
    [GetHashKey("des_vaultdoor001_root006")] = true,
    [GetHashKey("des_vaultdoor001_skin001")] = true,
    [GetHashKey("des_vaultdoor001_start")] = true,
    [GetHashKey("des_traincrash_root6")] = true,
    [GetHashKey("prop_ld_vault_door")] = true,
    [GetHashKey("prop_vault_door_scene")] = true,
    [GetHashKey("prop_vault_door_scene")] = true,
    [GetHashKey("prop_vault_shutter")] = true,
    [GetHashKey("p_fin_vaultdoor_s")] = true,
    [GetHashKey("v_ilev_bk_vaultdoor")] = true,
    [GetHashKey("prop_gold_vault_fence_l")] = true,
    [GetHashKey("prop_gold_vault_fence_r")] = true,
    [GetHashKey("prop_gold_vault_gate_01")] = true,
    [GetHashKey("prop_boolk_vaultdoor")] = true,
    [GetHashKey("des_traincrash_root7")] = true,
    [GetHashKey("prop_flag_russia")] = true,
    [GetHashKey("prop_flag_russia_s")] = true,
    [GetHashKey("prop_flag_s")] = true,
    [GetHashKey("ch2_03c_props_rrlwindmill_lod")] = true,
    [GetHashKey("prop_flag_sa")] = true,
    [GetHashKey("prop_flag_sapd")] = true,
    [GetHashKey("prop_flag_sapd_s")] = true,
    [GetHashKey("prop_flag_sa_s")] = true,
    [GetHashKey("prop_flag_scotland")] = true,
    [GetHashKey("prop_flag_scotland_s")] = true,
    [GetHashKey("prop_flag_sheriff")] = true,
    [GetHashKey("prop_flag_sheriff_s")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_yacht_lounger")] = true,
    [GetHashKey("prop_yacht_seat_01")] = true,
    [GetHashKey("prop_yacht_seat_02")] = true,
    [GetHashKey("prop_yacht_seat_03")] = true,
    [GetHashKey("marina_xr_rocks_02")] = true,
    [GetHashKey("marina_xr_rocks_03")] = true,
    [GetHashKey("prop_test_rocks01")] = true,
    [GetHashKey("prop_test_rocks02")] = true,
    [GetHashKey("prop_test_rocks03")] = true,
    [GetHashKey("prop_test_rocks04")] = true,
    [GetHashKey("marina_xr_rocks_04")] = true,
    [GetHashKey("marina_xr_rocks_05")] = true,
    [GetHashKey("marina_xr_rocks_06")] = true,
    [GetHashKey("prop_yacht_table_01")] = true,
    [GetHashKey("csx_searocks_02")] = true,
    [GetHashKey("csx_searocks_03")] = true,
    [GetHashKey("csx_searocks_04")] = true,
    [GetHashKey("csx_searocks_05")] = true,
    [GetHashKey("csx_searocks_06")] = true,
    [GetHashKey("p_yacht_chair_01_s")] = true,
    [GetHashKey("p_yacht_sofa_01_s")] = true,
    [GetHashKey("prop_yacht_table_02")] = true,
    [GetHashKey("csx_coastboulder_00")] = true,
    [GetHashKey("csx_coastboulder_01")] = true,
    [GetHashKey("csx_coastboulder_02")] = true,
    [GetHashKey("csx_coastboulder_03")] = true,
    [GetHashKey("csx_coastboulder_04")] = true,
    [GetHashKey("csx_coastboulder_05")] = true,
    [GetHashKey("csx_coastboulder_06")] = true,
    [GetHashKey("csx_coastboulder_07")] = true,
    [GetHashKey("csx_coastrok1")] = true,
    [GetHashKey("csx_coastrok2")] = true,
    [GetHashKey("csx_coastrok3")] = true,
    [GetHashKey("csx_coastrok4")] = true,
    [GetHashKey("csx_coastsmalrock_01")] = true,
    [GetHashKey("csx_coastsmalrock_02")] = true,
    [GetHashKey("csx_coastsmalrock_03")] = true,
    [GetHashKey("csx_coastsmalrock_04")] = true,
    [GetHashKey("csx_coastsmalrock_05")] = true,
    [GetHashKey("prop_yacht_table_03")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("p_gasmask_s")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_01")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_03")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_04")] = true,
    [GetHashKey("prop_fnclink_02a")] = true,
    [GetHashKey("prop_fnclink_02b")] = true,
    [GetHashKey("prop_fnclink_02c")] = true,
    [GetHashKey("prop_fnclink_02a_sdt")] = true,
    [GetHashKey("apa_mp_h_yacht_barstool_01")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_01")] = true,
    [GetHashKey("p_cs_mp_jet_01_s")] = true,
    [GetHashKey("p_med_jet_01_s")] = true,
    [GetHashKey("prop_med_jet_01")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_02")] = true,
    [GetHashKey("prop_gas_pump_1a")] = true,
    [GetHashKey("prop_gas_pump_1b")] = true,
    [GetHashKey("prop_gas_pump_1c")] = true,
    [GetHashKey("prop_gas_pump_1d")] = true,
    [GetHashKey("prop_gas_pump_old2")] = true,
    [GetHashKey("prop_vintage_pump")] = true,
    [GetHashKey("prop_gas_pump_old3")] = true,
    [GetHashKey("apa_mp_h_yacht_coffee_table_01")] = true,
    [GetHashKey("apa_mp_h_yacht_coffee_table_02")] = true,
    [GetHashKey("apa_mp_h_yacht_floor_lamp_01")] = true,
    [GetHashKey("apa_mp_h_yacht_side_table_01")] = true,
    [GetHashKey("apa_mp_h_yacht_side_table_02")] = true,
    [GetHashKey("apa_mp_h_yacht_sofa_01")] = true,
    [GetHashKey("apa_mp_h_yacht_sofa_02")] = true,
    [GetHashKey("apa_mp_h_yacht_stool_01")] = true,
    [GetHashKey("apa_mp_h_yacht_strip_chair_01")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_01")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_02")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_03")] = true,
    [GetHashKey("prop_flag_columbia")] = true,
    [GetHashKey("apa_mp_apa_yacht_o2_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o2_rail_b")] = true,
    [GetHashKey("apa_mp_apa_yacht_o3_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o3_rail_b")] = true,
    [GetHashKey("apa_mp_apa_yacht_option1")] = true,
    [GetHashKey("proc_searock_01")] = true,
    [GetHashKey("apa_mp_h_yacht_")] = true,
    [GetHashKey("apa_mp_apa_yacht_option1_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2_colb")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_colb")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_colc")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cold")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cole")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_cam")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple003")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple1")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple2")] = true,
    [GetHashKey("apa_mp_apa_yacht_radar_01a")] = true,
    [GetHashKey("apa_mp_apa_yacht_win")] = true,
    [GetHashKey("prop_crashed_heli")] = true,
    [GetHashKey("apa_mp_apa_yacht_door")] = true,
    [GetHashKey("prop_shamal_crash")] = true,
    [GetHashKey("xm_prop_x17_shamal_crash")] = true,
    [GetHashKey("apa_mp_apa_yacht_door2")] = true,
    [GetHashKey("apa_mp_apa_yacht")] = true,
    [GetHashKey("prop_flagpole_2b")] = true,
    [GetHashKey("prop_flagpole_2c")] = true,
    [GetHashKey("prop_flag_canada")] = true,
    [GetHashKey("apa_prop_yacht_float_1a")] = true,
    [GetHashKey("apa_prop_yacht_float_1b")] = true,
    [GetHashKey("apa_prop_yacht_glass_01")] = true,
    [GetHashKey("apa_prop_yacht_glass_02")] = true,
    [GetHashKey("apa_prop_yacht_glass_03")] = true,
    [GetHashKey("apa_prop_yacht_glass_04")] = true,
    [GetHashKey("apa_prop_yacht_glass_05")] = true,
    [GetHashKey("apa_prop_yacht_glass_06")] = true,
    [GetHashKey("apa_prop_yacht_glass_07")] = true,
    [GetHashKey("apa_prop_yacht_glass_08")] = true,
    [GetHashKey("apa_prop_yacht_glass_09")] = true,
    [GetHashKey("apa_prop_yacht_glass_10")] = true,
    [GetHashKey("prop_flag_canada_s")] = true,
    [GetHashKey("prop_flag_eu")] = true,
    [GetHashKey("prop_flag_eu_s")] = true,
    [GetHashKey("prop_target_blue_arrow")] = true,
    [GetHashKey("prop_target_orange_arrow")] = true,
    [GetHashKey("prop_target_purp_arrow")] = true,
    [GetHashKey("prop_target_red_arrow")] = true,
    [GetHashKey("apa_prop_flag_argentina")] = true,
    [GetHashKey("apa_prop_flag_australia")] = true,
    [GetHashKey("apa_prop_flag_austria")] = true,
    [GetHashKey("apa_prop_flag_belgium")] = true,
    [GetHashKey("apa_prop_flag_brazil")] = true,
    [GetHashKey("apa_prop_flag_canadat_yt")] = true,
    [GetHashKey("apa_prop_flag_china")] = true,
    [GetHashKey("apa_prop_flag_columbia")] = true,
    [GetHashKey("apa_prop_flag_croatia")] = true,
    [GetHashKey("apa_prop_flag_czechrep")] = true,
    [GetHashKey("apa_prop_flag_denmark")] = true,
    [GetHashKey("apa_prop_flag_england")] = true,
    [GetHashKey("apa_prop_flag_eu_yt")] = true,
    [GetHashKey("apa_prop_flag_finland")] = true,
    [GetHashKey("apa_prop_flag_france")] = true,
    [GetHashKey("apa_prop_flag_german_yt")] = true,
    [GetHashKey("apa_prop_flag_hungary")] = true,
    [GetHashKey("apa_prop_flag_ireland")] = true,
    [GetHashKey("apa_prop_flag_israel")] = true,
    [GetHashKey("apa_prop_flag_italy")] = true,
    [GetHashKey("apa_prop_flag_jamaica")] = true,
    [GetHashKey("apa_prop_flag_japan_yt")] = true,
    [GetHashKey("apa_prop_flag_canada_yt")] = true,
    [GetHashKey("apa_prop_flag_lstein")] = true,
    [GetHashKey("apa_prop_flag_malta")] = true,
    [GetHashKey("apa_prop_flag_mexico_yt")] = true,
    [GetHashKey("apa_prop_flag_netherlands")] = true,
    [GetHashKey("apa_prop_flag_newzealand")] = true,
    [GetHashKey("apa_prop_flag_nigeria")] = true,
    [GetHashKey("apa_prop_flag_norway")] = true,
    [GetHashKey("apa_prop_flag_palestine")] = true,
    [GetHashKey("apa_prop_flag_poland")] = true,
    [GetHashKey("apa_prop_flag_portugal")] = true,
    [GetHashKey("apa_prop_flag_puertorico")] = true,
    [GetHashKey("apa_prop_flag_russia_yt")] = true,
    [GetHashKey("apa_prop_flag_scotland_yt")] = true,
    [GetHashKey("apa_prop_flag_script")] = true,
    [GetHashKey("apa_prop_flag_slovakia")] = true,
    [GetHashKey("apa_prop_flag_slovenia")] = true,
    [GetHashKey("apa_prop_flag_southafrica")] = true,
    [GetHashKey("apa_prop_flag_southkorea")] = true,
    [GetHashKey("apa_prop_flag_spain")] = true,
    [GetHashKey("apa_prop_flag_sweden")] = true,
    [GetHashKey("apa_prop_flag_switzerland")] = true,
    [GetHashKey("apa_prop_flag_turkey")] = true,
    [GetHashKey("apa_prop_flag_uk_yt")] = true,
    [GetHashKey("apa_prop_flag_us_yt")] = true,
    [GetHashKey("apa_prop_flag_wales")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("prop_flag_france")] = true,
    [GetHashKey("prop_flag_france_s")] = true,
    [GetHashKey("prop_flag_german")] = true,
    [GetHashKey("prop_flag_german_s")] = true,
    [GetHashKey("prop_flag_ireland")] = true,
    [GetHashKey("prop_flag_ireland_s")] = true,
    [GetHashKey("prop_flag_japan")] = true,
    [GetHashKey("prop_flag_japan_s")] = true,
    [GetHashKey("prop_flag_ls")] = true,
    [GetHashKey("prop_flag_lsfd")] = true,
    [GetHashKey("prop_flag_lsfd_s")] = true,
    [GetHashKey("prop_flag_lsservices")] = true,
    [GetHashKey("prop_flag_lsservices_s")] = true,
    [GetHashKey("prop_flag_ls_s")] = true,
    [GetHashKey("prop_flag_mexico")] = true,
    [GetHashKey("prop_flag_mexico_s")] = true,
    [GetHashKey("prop_flag_russia")] = true,
    [GetHashKey("prop_flag_russia_s")] = true,
    [GetHashKey("prop_flag_s")] = true,
    [GetHashKey("prop_flag_sa")] = true,
    [GetHashKey("prop_flag_sapd")] = true,
    [GetHashKey("prop_flag_sapd_s")] = true,
    [GetHashKey("prop_flag_sa_s")] = true,
    [GetHashKey("prop_flag_scotland")] = true,
    [GetHashKey("prop_flag_scotland_s")] = true,
    [GetHashKey("prop_flag_sheriff")] = true,
    [GetHashKey("prop_flag_sheriff_s")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("prop_flamingo")] = true,
    [GetHashKey("prop_air_bigradar_l1")] = true,
    [GetHashKey("prop_air_bigradar_l2")] = true,
    [GetHashKey("prop_air_bigradar_slod")] = true,
    [GetHashKey("p_fib_rubble_s")] = true,
    [GetHashKey("prop_money_bag_01")] = true,
    [GetHashKey("p_cs_mp_jet_01_s")] = true,
    [GetHashKey("prop_poly_bag_money")] = true,
    [GetHashKey("prop_air_radar_01")] = true,
    [GetHashKey("hei_prop_carrier_radar_1")] = true,
    [GetHashKey("prop_air_bigradar")] = true,
    [GetHashKey("prop_carrier_radar_1_l1")] = true,
    [GetHashKey("prop_asteroid_01")] = true,
    [GetHashKey("prop_xmas_ext")] = true,
    [GetHashKey("p_oil_pjack_01_amo")] = true,
    [GetHashKey("p_oil_pjack_01_s")] = true,
    [GetHashKey("p_oil_pjack_02_amo")] = true,
    [GetHashKey("p_oil_pjack_03_amo")] = true,
    [GetHashKey("p_oil_pjack_02_s")] = true,
    [GetHashKey("p_oil_pjack_03_s")] = true,
    [GetHashKey("prop_aircon_l_03")] = true,
    [GetHashKey("prop_med_jet_01")] = true,
    [GetHashKey("p_med_jet_01_s")] = true,
    [GetHashKey("hei_prop_carrier_jet")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_01")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_02")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_04")] = true,
    [GetHashKey("bkr_prop_biker_bblock_huge_05")] = true,
    [GetHashKey("hei_prop_heist_emp")] = true,
    [GetHashKey("prop_weed_01")] = true,
    [GetHashKey("prop_air_bigradar")] = true,
    [GetHashKey("prop_juicestand")] = true,
    [GetHashKey("prop_lev_des_barge_02")] = true,
    [GetHashKey("hei_prop_carrier_defense_01")] = true,
    [GetHashKey("prop_aircon_m_04")] = true,
    [GetHashKey("prop_mp_ramp_03")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("ch3_12_animplane1_lod")] = true,
    [GetHashKey("ch3_12_animplane2_lod")] = true,
    [GetHashKey("hei_prop_hei_pic_pb_plane")] = true,
    [GetHashKey("light_plane_rig")] = true,
    [GetHashKey("prop_cs_plane_int_01")] = true,
    [GetHashKey("prop_dummy_plane")] = true,
    [GetHashKey("prop_mk_plane")] = true,
    [GetHashKey("v_44_planeticket")] = true,
    [GetHashKey("prop_planer_01")] = true,
    [GetHashKey("ch3_03_cliffrocks03b_lod")] = true,
    [GetHashKey("ch3_04_rock_lod_02")] = true,
    [GetHashKey("csx_coastsmalrock_01_")] = true,
    [GetHashKey("csx_coastsmalrock_02_")] = true,
    [GetHashKey("csx_coastsmalrock_03_")] = true,
    [GetHashKey("csx_coastsmalrock_04_")] = true,
    [GetHashKey("mp_player_introck")] = true,
    [GetHashKey("Heist_Yacht")] = true,
    [GetHashKey("csx_coastsmalrock_05_")] = true,
    [GetHashKey("mp_player_int_rock")] = true,
    [GetHashKey("mp_player_introck")] = true,
    [GetHashKey("prop_flagpole_1a")] = true,
    [GetHashKey("prop_flagpole_2a")] = true,
    [GetHashKey("prop_flagpole_3a")] = true,
    [GetHashKey("prop_a4_pile_01")] = true,
    [GetHashKey("cs2_10_sea_rocks_lod")] = true,
    [GetHashKey("cs2_11_sea_marina_xr_rocks_03_lod")] = true,
    [GetHashKey("prop_gold_cont_01")] = true,
    [GetHashKey("prop_hydro_platform")] = true,
    [GetHashKey("ch3_04_viewplatform_slod")] = true,
    [GetHashKey("ch2_03c_rnchstones_lod")] = true,
    [GetHashKey("proc_mntn_stone01")] = true,
    [GetHashKey("prop_beachflag_le")] = true,
    [GetHashKey("proc_mntn_stone02")] = true,
    [GetHashKey("cs2_10_sea_shipwreck_lod")] = true,
    [GetHashKey("des_shipsink_02")] = true,
    [GetHashKey("prop_dock_shippad")] = true,
    [GetHashKey("des_shipsink_03")] = true,
    [GetHashKey("des_shipsink_04")] = true,
    [GetHashKey("prop_mk_flag")] = true,
    [GetHashKey("prop_mk_flag_2")] = true,
    [GetHashKey("proc_mntn_stone03")] = true,
    [GetHashKey("FreeModeMale01")] = true,
    [GetHashKey("rsn_os_specialfloatymetal_n")] = true,
    [GetHashKey("rsn_os_specialfloatymetal")] = true,
    [GetHashKey("cs1_09_sea_ufo")] = true,
    [GetHashKey("rsn_os_specialfloaty2_light2")] = true,
    [GetHashKey("rsn_os_specialfloaty2_light")] = true,
    [GetHashKey("rsn_os_specialfloaty2")] = true,
    [GetHashKey("rsn_os_specialfloatymetal_n")] = true,
    [GetHashKey("rsn_os_specialfloatymetal")] = true,
    [GetHashKey("P_Spinning_Anus_S_Main")] = true,
    [GetHashKey("P_Spinning_Anus_S_Root")] = true,
    [GetHashKey("cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a")] = true,
    [GetHashKey("sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a")] = true,
    [GetHashKey("rnbj_wallsigns_0001")] = true,
    [GetHashKey("proc_sml_stones01")] = true,
    [GetHashKey("proc_sml_stones02")] = true,
    [GetHashKey("maverick")] = true,
    [GetHashKey("Miljet")] = true,
    [GetHashKey("proc_sml_stones03")] = true,
    [GetHashKey("proc_stones_01")] = true,
    [GetHashKey("proc_stones_02")] = true,
    [GetHashKey("proc_stones_03")] = true,
    [GetHashKey("proc_stones_04")] = true,
    [GetHashKey("proc_stones_05")] = true,
    [GetHashKey("proc_stones_06")] = true,
    [GetHashKey("prop_coral_stone_03")] = true,
    [GetHashKey("prop_coral_stone_04")] = true,
    [GetHashKey("ar_prop_ar_stunt_block_01a")] = true,
    [GetHashKey("ar_prop_ar_stunt_block_01b")] = true,
    [GetHashKey("prop_mp_ramp_03_tu")] = true,
    [GetHashKey("prop_container_01mb")] = true,
    [GetHashKey("prop_container_03_ld")] = true,
    [GetHashKey("prop_container_03mb")] = true,
    [GetHashKey("prop_container_03b")] = true,
    [GetHashKey("prop_container_05a")] = true,
    [GetHashKey("prop_container_hole")] = true,
    [GetHashKey("prop_container_old1")] = true,
    [GetHashKey("prop_container_ld_pu")] = true,
    [GetHashKey("prop_ld_container")] = true,
    [GetHashKey("prop_dummy_plane")] = true,
    [GetHashKey("prop_mk_plane")] = true,
    [GetHashKey("prop_cs_plane_int_01")] = true,
    [GetHashKey("lts_prop_lts_ramp_03")] = true,
    [GetHashKey("prop_byard_rampold_cr")] = true,
    [GetHashKey("prop_gascyl_ramp_01")] = true,
    [GetHashKey("prop_mp_ramp_03")] = true,
    [GetHashKey("prop_mp_ramp_02_tu")] = true,
    [GetHashKey("prop_mp_ramp_03_tu")] = true,
    [GetHashKey("stt_prop_stunt_wideramp")] = true,
    [GetHashKey("prop_gravestones_01a")] = true,
    [GetHashKey("dump")] = true,
    [GetHashKey("prop_gravestones_02a")] = true,
    [GetHashKey("prop_gravestones_03a")] = true,
    [GetHashKey("prop_gravestones_04a")] = true,
    [GetHashKey("prop_gravestones_05a")] = true,
    [GetHashKey("prop_gravestones_06a")] = true,
    [GetHashKey("prop_gravestones_07a")] = true,
    [GetHashKey("prop_gravestones_08a")] = true,
    [GetHashKey("prop_gravestones_09a")] = true,
    [GetHashKey("prop_gravestones_10a")] = true,
    [GetHashKey("prop_prlg_gravestone_05a_l1")] = true,
    [GetHashKey("prop_prlg_gravestone_06a")] = true,
    [GetHashKey("test_prop_gravestones_04a")] = true,
    [GetHashKey("test_prop_gravestones_05a")] = true,
    [GetHashKey("test_prop_gravestones_07a")] = true,
    [GetHashKey("test_prop_gravestones_08a")] = true,
    [GetHashKey("test_prop_gravestones_09a")] = true,
    [GetHashKey("prop_prlg_gravestone_01a")] = true,
    [GetHashKey("prop_prlg_gravestone_02a")] = true,
    [GetHashKey("prop_prlg_gravestone_03a")] = true,
    [GetHashKey("prop_prlg_gravestone_04a")] = true,
    [GetHashKey("prop_stoneshroom1")] = true,
    [GetHashKey("prop_stoneshroom2")] = true,
    [GetHashKey("v_res_fa_stones01")] = true,
    [GetHashKey("test_prop_gravestones_01a")] = true,
    [GetHashKey("test_prop_gravestones_02a")] = true,
    [GetHashKey("prop_prlg_gravestone_05a")] = true,
    [GetHashKey("FreemodeFemale01")] = true,
    [GetHashKey("p_cablecar_s")] = true,
    [GetHashKey("stt_prop_stunt_tube_l")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("stt_prop_stunt_jump15")] = true,
    [GetHashKey("stt_prop_stunt_jump30")] = true,
    [GetHashKey("stt_prop_stunt_jump45")] = true,
    [GetHashKey("p_spinning_anus_s")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("hei_prop_heist_tug")] = true,
    [GetHashKey("prop_air_bigradar")] = true,
    [GetHashKey("p_oil_slick_01")] = true,
    [GetHashKey("prop_dummy_01")] = true,
    [GetHashKey("hei_prop_heist_emp")] = true,
    [GetHashKey("p_tram_cash_s")] = true,
    [GetHashKey("hw1_blimp_ce2")] = true,
    [GetHashKey("prop_fire_exting_1a")] = true,
    [GetHashKey("prop_fire_exting_1b")] = true,
    [GetHashKey("prop_fire_exting_2a")] = true,
    [GetHashKey("prop_fire_exting_3a")] = true,
    [GetHashKey("hw1_blimp_ce2_lod")] = true,
    [GetHashKey("hw1_blimp_ce_lod")] = true,
    [GetHashKey("hw1_blimp_cpr003")] = true,
    [GetHashKey("hw1_blimp_cpr_null")] = true,
    [GetHashKey("hw1_blimp_cpr_null2")] = true,
    [GetHashKey("prop_lev_des_barage_02")] = true,
    [GetHashKey("hei_prop_carrier_defense_01")] = true,
    [GetHashKey("prop_juicestand")] = true,
    [GetHashKey("S_M_M_MovAlien_01")] = true,
    [GetHashKey("s_m_m_movalien_01")] = true,
    [GetHashKey("s_m_m_movallien_01")] = true,
    [GetHashKey("u_m_y_babyd")] = true,
    [GetHashKey("CS_Orleans")] = true,
    [GetHashKey("A_M_Y_ACult_01")] = true,
    [GetHashKey("S_M_M_MovSpace_01")] = true,
    [GetHashKey("U_M_Y_Zombie_01")] = true,
    [GetHashKey("s_m_y_blackops_01")] = true,
    [GetHashKey("a_f_y_topless_01")] = true,
    [GetHashKey("s_f_y_hooker_03")] = true,
    [GetHashKey("v_ilev_found_cranebucket")] = true,
    [GetHashKey("p_cs_sub_hook_01_s")] = true,
    [GetHashKey("a_c_dolphin")] = true,
    [GetHashKey("a_c_fish")] = true,
    [GetHashKey("hei_prop_heist_hook_01")] = true,
    [GetHashKey("prop_rope_hook_01")] = true,
    [GetHashKey("prop_sub_crane_hook")] = true,
    [GetHashKey("prop_vehicle_hook")] = true,
    [GetHashKey("prop_v_hook_s")] = true,
    [GetHashKey("prop_dock_crane_02_hook")] = true,
    [GetHashKey("prop_winch_hook_long")] = true,
    [GetHashKey("a_c_humpback")] = true,
    [GetHashKey("a_c_killerwhale")] = true,
    [GetHashKey("prop_coathook_01")] = true,
    [GetHashKey("prop_cs_sub_hook_01")] = true,
    [GetHashKey("a_c_rhesus")] = true,
    [GetHashKey("a_c_sharktiger")] = true,
    [GetHashKey("a_c_stingray")] = true,
    [GetHashKey("CS_Orleans")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("prop_Ld_ferris_wheel")] = true,
    [GetHashKey("p_tram_crash_s")] = true,
    [GetHashKey("p_oil_slick_01")] = true,
    [GetHashKey("p_parachute1_s")] = true,
    [GetHashKey("p_cablecar_s")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_lev_des_barge_02")] = true,
    [GetHashKey("prop_lev_des_barge_01")] = true,
    [GetHashKey("prop_sculpt_fix")] = true,
    [GetHashKey("prop_flagpole_2b")] = true,
    [GetHashKey("prop_flagpole_2c")] = true,
    [GetHashKey("prop_winch_hook_short")] = true,
    [GetHashKey("prop_flag_canada")] = true,
    [GetHashKey("prop_flag_canada_s")] = true,
    [GetHashKey("prop_flag_eu")] = true,
    [GetHashKey("prop_flag_eu_s")] = true,
    [GetHashKey("prop_flag_france")] = true,
    [GetHashKey("prop_flag_france_s")] = true,
    [GetHashKey("prop_flag_german")] = true,
    [GetHashKey("prop_ld_hook")] = true,
    [GetHashKey("prop_flag_german_s")] = true,
    [GetHashKey("prop_flag_ireland")] = true,
    [GetHashKey("prop_flag_ireland_s")] = true,
    [GetHashKey("prop_flag_japan")] = true,
    [GetHashKey("prop_flag_japan_s")] = true,
    [GetHashKey("prop_flag_ls")] = true,
    [GetHashKey("prop_flag_lsfd")] = true,
    [GetHashKey("prop_flag_lsfd_s")] = true,
    [GetHashKey("prop_cable_hook_01")] = true,
    [GetHashKey("prop_flag_lsservices")] = true,
    [GetHashKey("prop_flag_lsservices_s")] = true,
    [GetHashKey("prop_flag_ls_s")] = true,
    [GetHashKey("prop_flag_mexico")] = true,
    [GetHashKey("prop_flag_mexico_s")] = true,
    [GetHashKey("csx_coastboulder_00")] = true,
    [GetHashKey("des_tankercrash_01")] = true,
    [GetHashKey("des_tankerexplosion_01")] = true,
    [GetHashKey("des_tankerexplosion_02")] = true,
    [GetHashKey("des_trailerparka_02")] = true,
    [GetHashKey("des_trailerparkb_02")] = true,
    [GetHashKey("des_trailerparkc_02")] = true,
    [GetHashKey("des_trailerparkd_02")] = true,
    [GetHashKey("des_traincrash_root2")] = true,
    [GetHashKey("des_traincrash_root3")] = true,
    [GetHashKey("des_traincrash_root4")] = true,
    [GetHashKey("des_traincrash_root5")] = true,
    [GetHashKey("des_finale_vault_end")] = true,
    [GetHashKey("des_finale_vault_root001")] = true,
    [GetHashKey("des_finale_vault_root002")] = true,
    [GetHashKey("des_finale_vault_root003")] = true,
    [GetHashKey("des_finale_vault_root004")] = true,
    [GetHashKey("des_finale_vault_start")] = true,
    [GetHashKey("des_vaultdoor001_root001")] = true,
    [GetHashKey("des_vaultdoor001_root002")] = true,
    [GetHashKey("des_vaultdoor001_root003")] = true,
    [GetHashKey("des_vaultdoor001_root004")] = true,
    [GetHashKey("des_vaultdoor001_root005")] = true,
    [GetHashKey("des_vaultdoor001_root006")] = true,
    [GetHashKey("des_vaultdoor001_skin001")] = true,
    [GetHashKey("des_vaultdoor001_start")] = true,
    [GetHashKey("des_traincrash_root6")] = true,
    [GetHashKey("prop_ld_vault_door")] = true,
    [GetHashKey("prop_vault_door_scene")] = true,
    [GetHashKey("prop_vault_door_scene")] = true,
    [GetHashKey("prop_vault_shutter")] = true,
    [GetHashKey("p_fin_vaultdoor_s")] = true,
    [GetHashKey("v_ilev_bk_vaultdoor")] = true,
    [GetHashKey("prop_gold_vault_fence_l")] = true,
    [GetHashKey("prop_gold_vault_fence_r")] = true,
    [GetHashKey("prop_gold_vault_gate_01")] = true,
    [GetHashKey("prop_boolk_vaultdoor")] = true,
    [GetHashKey("des_traincrash_root7")] = true,
    [GetHashKey("prop_flag_russia")] = true,
    [GetHashKey("prop_flag_russia_s")] = true,
    [GetHashKey("prop_flag_s")] = true,
    [GetHashKey("ch2_03c_props_rrlwindmill_lod")] = true,
    [GetHashKey("prop_flag_sa")] = true,
    [GetHashKey("prop_flag_sapd")] = true,
    [GetHashKey("prop_flag_sapd_s")] = true,
    [GetHashKey("prop_flag_sa_s")] = true,
    [GetHashKey("prop_flag_scotland")] = true,
    [GetHashKey("prop_flag_scotland_s")] = true,
    [GetHashKey("prop_flag_sheriff")] = true,
    [GetHashKey("prop_flag_sheriff_s")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_yacht_lounger")] = true,
    [GetHashKey("prop_yacht_seat_01")] = true,
    [GetHashKey("prop_yacht_seat_02")] = true,
    [GetHashKey("prop_yacht_seat_03")] = true,
    [GetHashKey("marina_xr_rocks_02")] = true,
    [GetHashKey("marina_xr_rocks_03")] = true,
    [GetHashKey("prop_test_rocks01")] = true,
    [GetHashKey("prop_test_rocks02")] = true,
    [GetHashKey("prop_test_rocks03")] = true,
    [GetHashKey("prop_test_rocks04")] = true,
    [GetHashKey("marina_xr_rocks_04")] = true,
    [GetHashKey("marina_xr_rocks_05")] = true,
    [GetHashKey("marina_xr_rocks_06")] = true,
    [GetHashKey("prop_yacht_table_01")] = true,
    [GetHashKey("csx_searocks_02")] = true,
    [GetHashKey("csx_searocks_03")] = true,
    [GetHashKey("csx_searocks_04")] = true,
    [GetHashKey("csx_searocks_05")] = true,
    [GetHashKey("csx_searocks_06")] = true,
    [GetHashKey("p_yacht_chair_01_s")] = true,
    [GetHashKey("p_yacht_sofa_01_s")] = true,
    [GetHashKey("prop_yacht_table_02")] = true,
    [GetHashKey("csx_coastboulder_00")] = true,
    [GetHashKey("csx_coastboulder_01")] = true,
    [GetHashKey("csx_coastboulder_02")] = true,
    [GetHashKey("csx_coastboulder_03")] = true,
    [GetHashKey("csx_coastboulder_04")] = true,
    [GetHashKey("csx_coastboulder_05")] = true,
    [GetHashKey("csx_coastboulder_06")] = true,
    [GetHashKey("csx_coastboulder_07")] = true,
    [GetHashKey("csx_coastrok1")] = true,
    [GetHashKey("csx_coastrok2")] = true,
    [GetHashKey("csx_coastrok3")] = true,
    [GetHashKey("csx_coastrok4")] = true,
    [GetHashKey("csx_coastsmalrock_01")] = true,
    [GetHashKey("csx_coastsmalrock_02")] = true,
    [GetHashKey("blimp")] = true,
    [GetHashKey("p_crahsed_heli_s")] = true,
    [GetHashKey("csx_coastsmalrock_03")] = true,
    [GetHashKey("csx_coastsmalrock_04")] = true,
    [GetHashKey("csx_coastsmalrock_05")] = true,
    [GetHashKey("prop_yacht_table_03")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("p_gasmask_s")] = true,
    [GetHashKey("prop_flamingo")] = true,
    [GetHashKey("prop_gas_pump_old3")] = true,
    [GetHashKey("prop_vintage_pump")] = true,
    [GetHashKey("apa_mp_h_acc_box_trinket_01")] = true,
    [GetHashKey("prop_roundbailer02")] = true,
    [GetHashKey("prop_roundbailer01")] = true,
    [-685641702] = true,
    [-1230672010] = true,
    [-1404869155] = true,
    [-759902142] = true
 }
 
 MyricaBM.WhitelistedEntities = {
     [GetHashKey("prop_mp_cone_01")] = true,
     [GetHashKey("prop_mp_barrier_02b")] = true,
     [GetHashKey("prop_barrier_work05")] = true,
     [GetHashKey("prop_mp_arrow_barrier_01")] = true,
     [GetHashKey("prop_roadcone02a")] = true,
     [GetHashKey("prop_toolchest_01")] = true,
     [GetHashKey("p_ld_stinger_s")] = true,
     [GetHashKey("hei_prop_cash_crate_half_full")] = true,
     [GetHashKey("prop_studio_light_01")] = true,
     [GetHashKey("prop_studio_light_02")] = true,
     [GetHashKey("prop_studio_light_03")] = true,
     [GetHashKey("prop_kino_light_03")] = true,
     [GetHashKey("xm_prop_base_tripod_lampb")] = true,
     [GetHashKey("prop_dolly_01")] = true,
     [GetHashKey("prop_dolly_02")] = true,
     [GetHashKey("prop_generator_01a")] = true,
     [GetHashKey("prop_scrim_02")] = true,
     [GetHashKey("prop_tv_cam_02")] = true,
     [GetHashKey("prop_tv_stand_01")] = true,
     [GetHashKey("w_sg_sawnoff")] = true,
     [GetHashKey("w_lr_firework")] = true,
     [GetHashKey("w_sr_sniperrifle")] = true,
     [GetHashKey("w_ar_carbinerifle")] = true,
     [GetHashKey("w_ar_assaultrifle")] = true,
     [GetHashKey("w_ar_specialcarbine")] = true,
     [GetHashKey("w_ar_bullpuprifle")] = true,
     [GetHashKey("w_ar_advancedrifle")] = true,
     [GetHashKey("w_sg_assaultshotgun")] = true,
     [GetHashKey("w_sg_bullpupshotgun")] = true,
     [GetHashKey("w_sg_pumpshotgun")] = true,
     [GetHashKey("w_ar_musket")] = true,
     [GetHashKey("w_sr_heavysniper")] = true,
     [GetHashKey("w_sb_microsmg")] = true,
     [GetHashKey("w_sb_pdw")] = true,
     [GetHashKey("w_sb_assaultsmg")] = true,
     [GetHashKey("w_sb_smg")] = true,
     [GetHashKey("w_sb_gusenberg")] = true,
     [GetHashKey("w_sb_combatpdw")] = true,
     [GetHashKey("prop_cs_hand_radio")] = true,
     [GetHashKey("prop_cs_burger_01")] = true,
     [GetHashKey("prop_amb_phone")] = true,
     [GetHashKey("prop_ecola_can")] = true,
     [GetHashKey("p_amb_coffeecup_01")] = true,
     [GetHashKey("prop_plastic_cup_02")] = true,
     [GetHashKey("prop_amb_donut")] = true,
     [GetHashKey("prop_drink_whisky")] = true,
     [GetHashKey("prop_drink_redwine")] = true,
     [GetHashKey("prop_amb_beer_bottle")] = true,
     [GetHashKey("prop_sandwich_01")] = true,
     [GetHashKey("ba_prop_battle_glowstick_01")] = true,
     [GetHashKey("ba_prop_battle_hobby_horse")] = true,
     [GetHashKey("p_amb_brolly_01")] = true,
     [GetHashKey("prop_notepad_01")] = true,
     [GetHashKey("prop_pencil_01")] = true,
     [GetHashKey("hei_prop_heist_box")] = true,
     [GetHashKey("prop_single_rose")] = true,
     [GetHashKey("prop_cs_ciggy_01")] = true,
     [GetHashKey("hei_heist_sh_bong_01")] = true,
     [GetHashKey("prop_ld_suitcase_01")] = true,
     [GetHashKey("prop_security_case_01")] = true,
     [GetHashKey("prop_police_id_board")] = true,
     [GetHashKey("prop_champ_flute")] = true,
     [GetHashKey("prop_drink_champ")] = true,
     [GetHashKey("prop_cigar_01")] = true,
     [GetHashKey("prop_cigar_02")] = true,
     [GetHashKey("prop_acc_guitar_01")] = true,
     [GetHashKey("prop_el_guitar_01")] = true,
     [GetHashKey("prop_el_guitar_03")] = true,
     [GetHashKey("prop_novel_01")] = true,
     [GetHashKey("prop_snow_flower_02")] = true,
     [GetHashKey("v_ilev_mr_rasberryclean")] = true,
     [GetHashKey("p_michael_backpack_s")] = true,
     [GetHashKey("p_amb_clipboard_01")] = true,
     [GetHashKey("prop_tourist_map_01")] = true,
     [GetHashKey("prop_beggers_sign_03")] = true,
     [GetHashKey("prop_anim_cash_pile_01")] = true,
     [GetHashKey("prop_pap_camera_01")] = true,
     [GetHashKey("ba_prop_battle_champ_open")] = true,
     [GetHashKey("p_cs_joint_02")] = true,
     [GetHashKey("prop_amb_ciggy_01")] = true,
     [GetHashKey("prop_cs_tablet")] = true,
     [GetHashKey("prop_npc_phone_02")] = true,
     [GetHashKey("prop_ld_case_01")] = true,
     [GetHashKey("prop_sponge_01")] = true,
     [GetHashKey("prop_ld_flow_bottle")] = true,
     [GetHashKey("ng_proc_sodacan_01b")] = true,
     [GetHashKey("prop_v_cam_01")] = true,
     [GetHashKey("prop_v_bmike_01")] = true,
     [GetHashKey("p_ing_microphonel_01")] = true,
     [GetHashKey("w_me_nightstick")] = true,
     [GetHashKey("w_me_knife_01")] = true,
     [GetHashKey("w_me_hammer")] = true,
     [GetHashKey("w_me_gclub")] = true,
     [GetHashKey("w_me_bat")] = true,
     [GetHashKey("w_me_crowbar")] = true,
     [GetHashKey("p_cs_cuffs_02_s")] = true,
     [GetHashKey("prop_choc_ego")] = true,
     [GetHashKey("prop_bodyarmour_03")] = true,
     [GetHashKey("prop_food_bs_burger2")] = true,
     [GetHashKey("prop_ld_snack_01")] = true,
     [GetHashKey("p_parachute1_mp_s")] = true,
     [GetHashKey("gtaw_ladder_m")] = true,
     [GetHashKey("gtaw_ladder_l")] = true,
     [GetHashKey("gtaw_ladder_s")] = true,
     [GetHashKey("pd_tape")] = true,
     [GetHashKey("prop_juicestand")] = true
 }
 
 MyricaBM.BlacklistedPeds = {
     [GetHashKey("a_m_y_mexthug_01")] = {name = "MexThug", ban = true}, 
     [GetHashKey("a_c_boar")] = {name = "Boar", ban = true}, 
     [GetHashKey("a_c_sharkhammer")] = {name = "Sharkhammer", ban = false}, 
     [GetHashKey("a_c_chimp")] = {name = "Chimp", ban = true}, 
     [GetHashKey("a_c_hen")] = {name = "Hen", ban = true}, 
     [GetHashKey("a_c_humpback")] = {name = "Humpback", ban = true}, 
     [GetHashKey("a_c_killerwhale")] = {name = "Killerwhale", ban = true},
     [GetHashKey("a_c_rhesus")] = {name = "Rhesus", ban = true}, 
     [GetHashKey("a_c_sharktiger")] = {name = "SharkTiger", ban = false}, 
     [GetHashKey("u_m_y_zombie_01")] = {name = "Zombie", ban = true},
     [GetHashKey("a_m_m_acult_01")] = {name = "Acult01", ban = false},
     [GetHashKey("u_m_y_juggernaut_01")] = {name = "Juggernaut", ban = true},
 }
 
 