--[[ 
	Kronenburg Roleplay
	Copyright © GJSBRT <g@gijs.eu>

	This project is licensed under the terms of the Apache License 2.0 license.
	https://choosealicense.com/licenses/apache-2.0/
]]
 
 
resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

files {

	'data/**/carcols.meta',
	'data/**/carvariations.meta',
	'data/**/handling.meta',
	'data/**/vehiclelayouts.meta',
	'data/**/vehicles.meta',
}

files {
	'els/politiea6.xml',
	'els/boa1.xml',
	'els/bmicu.xml',
	'els/transportbus.xml',
	'els/takel.xml',
	'els/polbus3.xml',
	'els/douane2.xml',
	'els/douane3.xml',
	'els/mercedesb.xml',
	'els/hvito.xml',
	'els/beboot.xml',
	'els/polboot.xml',
	'els/polamarok.xml',
	'els/politielambo.xml',
	'els/panther.xml',
	'els/Kmaropel.xml',
	'els/VolkswagenAmarokKmar.xml',
	'els/politiebklasse.xml',
	'els/politie13.xml',
	'els/rs6avant20.xml',
	'els/politie12.xml',
	'els/politie15.xml',
	'els/politie20.xml',
	'els/wpu.xml',
	'els/AMBULANCE.xml',
	'els/AMBULANCE2.xml',
	'els/polkia.xml',
	'els/politie35.xml',
	'els/upolitietesla.xml',
	'els/kmarbmw.xml',
	'els/PolitieMotor.xml',
	'els/politieoffroad.xml',
	'els/PolitieT6.xml',
	'els/PolitieTouran.xml',
	'els/PolitieV70.xml',
	'els/PolitieVito.xml',
	'els/politiexc90.xml',
	'els/PRANGER.xml',
	'els/bearcat.xml',
	'els/rwsmotor.xml',
	'els/UPolitieA4.xml',
	'els/UPolitieArteon.xml',
	'els/pvwpassatk9.xml',
	'els/politie18.xml',
	'els/UPolitieBmw.xml',
	'els/politie29.xml',
	'els/UPolitieS4avant.xml',
	'els/audiq8ambu.xml',
	'els/anwbvito.xml',
	'els/kmara6.xml',
	'els/anwb2.xml',
	'els/anwbamarok.xml',
	'els/policegallardo.xml',
	'els/kmarmotor.xml',
	'els/kmarcar.xml',
	'els/kmotor.xml',
	'els/brandweer.xml',
	'els/brandweer2.xml',
	'els/brandweer3.xml',
	'els/brandmotor.xml',
	'els/poltransporter5.xml',
	'els/anwbt5.xml',
	'els/polrs6.xml',
	'els/wegenm.xml',
	'els/kmar2.xml',
	'els/kmar3.xml',
	'els/rrstPOL.xml',
	'els/dsibearcat.xml',
	'els/ambulance4.xml',
	'els/eod.xml',
	'els/tekstkar.xml',
	'els/lencome.xml',
	'els/politiepassat.xml',
	'els/ambum.xml',
	'els/ambumicu.xml',
	'els/ambumotor.xml',
	'els/amodelx.xml',
	'els/ambuamarok.xml',
	'els/eclass.xml',
	'els/dambulance.xml',
	'els/kmarbearcat.xml',
	'els/axc90.xml',
	'els/police3.xml', 
	'els/brandweer1.xml', 
	'els/brandweer5.xml', 
	'els/brandweer6.xml', 
	'els/kmart61.xml', 
	'els/polo.xml', 
	'els/rs6avant20.xml', 
	'els/a6unmarked.xml',
	'els/amb1.xml', 
	'els/amb2.xml',
	'els/mercml63.xml',
	'els/ov3.xml',
	'els/ov28.xml',
	'els/pamarok.xml',
	'els/polatbus.xml',
	'els/polaudi.xml',
	'els/polbmwx5v2.xml',
	'els/polbus3.xml',
	'els/poldvobus.xml',
	'els/polgolf7oov.xml',
	'els/politieamarok.xml',
	'els/PolitieAtBus.xml',
	'els/politieboot.xml',
	'els/politielicht.xml',
	'els/politieme.xml',
	'els/politieq7.xml',
	'els/PolitieTouranK9.xml',
	'els/politievito.xml',
	'els/poljeep.xml',
	'els/polmerc.xml',
	'els/polmotor.xml',
	'els/polmotor2.xml',
	'els/polmotor3.xml',
	'els/polmotorun.xml',
	'els/polpassat2.xml',
	'els/polrs6.xml',
	'els/polt6un.xml',
	'els/poltouran.xml',
	'els/poltouran2009.xml',
	'els/poltouran2016.xml',
	'els/poltransporter5.xml',
	'els/poltransporter6.xml',
	'els/polvito2016.xml',
	'els/polvolvovp.xml',
	'els/rrvogue.xml',
	'els/RWS1.xml',
	'els/rws2.xml',
	'els/t6unmarked.xml',
	'els/unmarkedx5.xml',
	'els/unmarked.xml',
	'els/upolitiea4.xml',
	'els/volkswagent6.xml',
	'els/vwtouareg.xml',
	'els/bmwg20.xml',
	'els/anwbtouran.xml',
	'els/aq7.xml'
}

	data_file 'VEHICLE_LAYOUTS_FILE'	'data/**/vehiclelayouts.meta'
	data_file 'HANDLING_FILE'			'data/**/handling.meta'
	data_file 'VEHICLE_METADATA_FILE'	'data/**/vehicles.meta'
	data_file 'CARCOLS_FILE'			'data/**/carcols.meta'
	data_file 'VEHICLE_VARIATION_FILE'	'data/**/carvariations.meta'

	client_scripts 'vehicle_names.lua'

	is_els 'true'