Strings = {
    -- blips
    ["purchasable_house"] = "Koopbaar huis",
    ["owned_house"] = "Uw huis",
    ["access_house"] = "Huis waarvan u een sleutel hebt",
    ["purchased_house"] = "Iemand's huis",

    ["purchasable_apartment"] = "Koopbaar appartement",
    ["owned_apartment"] = "Uw appartement",
    ["access_apartment"] = "Appartement waarvan uw sleutel hebt",
    ["purchased_apartment"] = "Iemand's appartement",

    ["ikea"] = "IKEA",
    ["robbery"] = "Inbraak",

    -- text for buttons
    ["buy_house"] = "Druk op ~INPUT_CONTEXT~ om te kopen ~b~%s~s~ (#%s) voor ~g~$%s~s~.",
    ["contact_rea"] = "Druk op ~INPUT_CONTEXT~ om te bezichtigen %s [#%s]",
    ["contact_rea_nopreview"] = "Neem contact op met een makelaar om dit huis te kopen.",
    ["enter"] = "Druk op ~INPUT_CONTEXT~ om het gebouw te betreden.",
    ["door"] = "Druk op ~INPUT_CONTEXT~ om het deurmenu te openen (%s)",
    ["enter_ikea"] = "Druk op ~INPUT_CONTEXT~ om IKEA te betreden.\nDruk op   ~INPUT_DETONATE~om meubilair te verkopen.",
    ["furnishing"] = "Voorwerp: %s\nSnelheid: %s ~INPUT_COVER~ ~INPUT_TALK~\nGebruik ~INPUT_WEAPON_WHEEL_PREV~ ~INPUT_WEAPON_WHEEL_NEXT~ om meubilair te bewegen op/neer\nGebruik ~INPUT_ATTACK~ ~INPUT_AIM~ om object te roteren\nGebruik ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ ~INPUT_CELLPHONE_UP~ ~INPUT_CELLPHONE_DOWN~ om object te bewegen\nDruk op ~INPUT_DETONATE~ om object te teleporteren naar je\nDruk op ~INPUT_FRONTEND_RDOWN~ om te bevestigen.\nDruk op ~INPUT_FRONTEND_RRIGHT~ om te annuleren.",
    ["access_storage"] = "Druk op ~INPUT_DETONATE~ om opslagruimte te betreden.",
    ["press_manage"] = "\nDruk op ~INPUT_DETONATE~ om huis te beheren.",
    ["enter_garage"] = "Druk op ~INPUT_CONTEXT~ om garage te betreden.",
    ["store_garage"] = "Druk op ~INPUT_CONTEXT~ om voertuig op te bergen.",
    ["breach_door"] = "\nDruk op ~INPUT_DETONATE~ om deur te doorbreken.",
    ["lockpick_door"] = "\nDruk op ~INPUT_DETONATE~ om deur te picklocken.",
    ["pole_dance"] = "Druk op ~INPUT_CONTEXT~ om paal te dansen",
    ["stop_dancing"] = "Druk op ~INPUT_VEH_DUCK~ om te stoppen met dansen",
    ["lap_dance"] = "Druk op ~INPUT_CONTEXT~ om te lapdansen\nDruk op   ~INPUT_VEH_EXIT~om te zitten",
    ["storage_wardrobe"] = "Opslagruimte of kleedruimte",
    ["storage_option"] = "Open opslagruimte",
    ["wardrobe_option"] = "Open kleedruimte",
    ["select_outfit"] = "Selecteer outfit",
    ["lockpicking"] = "Wanneer het slot langzaam gaat, dan bent u in de buurt.\nLockpicks over: %s\n\nGebruik ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ om slot te draaien\n~INPUT_FRONTEND_RDOWN~ ontgrendelen\n~INPUT_FRONTEND_RRIGHT~ Annuleren",

    -- ikea
    ["viewing_furniture"] = "Bladeren ~r~%s~s~.\nGebruik ~INPUT_REPLAY_BACK~ ~INPUT_REPLAY_ADVANCE~ om voorwerp te veranderen.\nGebruik ~INPUT_REPLAY_FFWD~ ~INPUT_REPLAY_REWIND~ om categorie te wijzigen.\nGebruik ~INPUT_MOVE_LEFT_ONLY~ ~INPUT_MOVE_RIGHT_ONLY~ om object te roteren.\nGebruik ~INPUT_MOVE_UP_ONLY~ ~INPUT_MOVE_DOWN_ONLY~ om in te zoomen.%s\nDruk op ~INPUT_FRONTEND_RDOWN~ om te kopen ~b~%s~s~ for ~g~$%s~s~.\nDruk op ~INPUT_FRONTEND_RRIGHT~ om IKEA te verlaten.",
    ["confirm_purchase"] = "koop ~b~%s~s~ voor ~g~$%s~s~?\n\n~INPUT_FRONTEND_RDOWN~ Koop\n~INPUT_FRONTEND_RRIGHT~ Annuleren",
    ["purchased"] = "Gekocht %s voor ~g~$%s~s~.",
    ["storage"] = "\nUw kunt spullen opbergen in dit voorwerp.",

    -- locked state
    ["locked"] = "Vergendeld",
    ["unlocked"] = "Ontgrendeld",
    
    -- text for menus 
    ["house_key"] = "Huissleutel",
    ["door_menu"] = "Deurmenu",
    ["toggle_lock"] = "Vergrendel / ontgrendel",
    ["exit"] = "Verlaten",
    ["furnish"] = "Meubilair",
    ["put_furniture"] = "Plaats meubilair",
    ["manage_furniture"] = "Beheer meubilair",
    ["amount_furniture"] = "x%s %s",
    ["confirm_house_purchase"] = "Gekocht %s voor <span style='color:lime'>$%s</span>",
    ["are_you_sure"] = "Koop %s?",
    ["what_interior"] = "Welk interieur wil u?",
    ["interior_number"] = "Interieur #%s",
    ["remove_furniture"] = "Verwijder %s?",
    ["inventory"] = "Opslagruimte",
    ["inventory_weapons"] = "Opslagruimte - wapens",
    ["inventory_items"] = "Opslagruimte - wapens",
    ["black_money"] = "Zwart geld: <span style='color:red'>$%s</span>",
    ["cash"] = "Geld: <span style='color:lime'>$%s</span>",
    ["put"] = "Leg voorwerp weg",
    ["get"] = "Pak voorwerp",
    ["deposit"] = "Wegleggen",
    ["withdraw"] = "Pakken",
    ["weapons"] = "Wapens",
    ["items"] = "voorwerpen",
    ["amount_of"] = "Aantal %s?",
    ["make_key_copy"] = "Maak een kopie van uw sleutel",
    ["resell_house"] = "Verkoop het huis voor <span style='color:lime'>$%s</span>",
    ["kick_someone_out"] = "Iemand uit huis kicken",
    ["kick_out?"] = "Kick %s?",
    ["kick_out"] = "Kick %s",
    ["preview"] = "Voorbeeld mogelijk interieur",
    ["previewing"] = "~h~Bezichtigen voorbeeld interieurs\n\n~h~Bezichtig interieur %s van de %s beschikbaar.\nGebruik ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ om ander interieur te bezichtigen\nDruk op ~INPUT_FRONTEND_RRIGHT~ om bezichtigen te stoppen.",
    ["previewing_nohelp"] = "~h~Bezichtig huis~h~\nNeem contact op met makelaar om dit huis te kopen.\nDruk op ~INPUT_FRONTEND_RRIGHT~ om bezichtigen te stoppen.",
    ["transfer_house"] = "Overdracht huis",
    ["transfer_property"] = "Eigendom overdragen naar %s?",
    ["none_nearby"] = "Er is niemand in de buurt.",
    ["yes"] = "Ja",
    ["no"] = "Nee",
    ["no_outfits"] = "Je hebt niet genoeg outfits bewaard.",
    ["confirm_delete"] = "Verwijder outfit \"%s\"?",
    ["equip_outfit"] = "Trek outfit aan",
    ["delete_outfit"] = "Verijder outfit",

    -- text for notifications
    ["no_spawn"] = "Onmogelijk vindbare locatie voor huis/appartement.\n\nVertel de server owner om meer huizen toe te voegen.",
    ["error_locked"] = "Kan het huis/appartement niet betreden - deur is vergrendeld.",
    ["not_near_door"] = "U bent niet in de buurt van de deur en kunt daarom niet vergrendelen / ontgrendelen.",
    ["must_be_number"] = "U moet een getal invoeren.",
    ["dont_have"] = "U heeft niet genoeg!",
    ["not_enough"] = "Er is niet genoeg in de opslagruimte.",
    ["cant_carry"] = "U kunt niet zoveel dragen!", 
    ["has_items"] = "Dit object heeft voorwerpen in zich, daarom kun je het niet pakken/verwijderen. Leeg eerst de opslag van het object!",
    ["someone_in_house_cant_sell"] = "Iemand is in het huis - u kunt het nu niet verkopen!",
    ["cant_own_more"] = "U kunt niet meer huizen hebben.",
    ["no_lockpicks"] = "U heeft niet genoeg lockpicks.",
    ["robbery_progress"] = "ALARM!! Iemand breekt in bij een huis! Check uw GPS!",
    ["you_got_kicked"] = "U bent uit het huis gezet.",
    ["house_spawned_transfer"] = "Iemand is binnen, u kunt het eigendom niet overdragen.",
    ["nolonger_nearby"] = "De speler is niet langer in de buurt.",
    ["nearby_storage"] = "Iemand is in de buurt, en daarom kunt u niet in de opslagruimte.",
    ["locked_door"] = "U heeft de deur vergrendeld.",
    ["unlocked_door"] = "U heeft de deur ontgrendeld.",

    -- text for loading
    ["purchasing"] = "Koop",
    ["removing_furniture"] = "Verwijderen meubilair",
    ["loading_object"] = "Inladen object",
    ["loading_storage"] = "Inladen opslag",

    -- other
    ["rotation"] = "Rotatie: %s",
    ["not_enough_cops"] = "Er is niet genoeg politie aanwezig!",
}